### ISSUE TITLE
This frozen actor has no footprint!

### ISSUE THREAD

**Issue by icharge** [OpenRA/ra2#123]
I have many Rhino tanks. (About 10) And attacking bot's base.
I think Rhino or something move on structure? and Error !

**exception.log**

> Red Alert 2 Mod at Version {DEV_VERSION}
> on map 3042ec5d8e8b2307270b0ea898075501a990766d (Heck Freezes Over by Westwood Studios).
> Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
> Runtime Version: .NET CLR 4.0.30319.42000
> Exception of type `System.ArgumentException`: This frozen actor has no footprint! Please report a bug!
> Actor Name: gapile
> Actor Location: 23,-19
> Input footprint: []
> Input footprint (shroud.Contains): []
> Input footprint (map.Contains): []
>    at OpenRA.Traits.FrozenActor..ctor(Actor self, PPos[] footprint, Shroud shroud, Boolean startsRevealed)
>    at OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass8_0.<Created>b__0(Player player, Int32 playerIndex)
>    at OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory)
>    at OpenRA.Mods.Common.Traits.FrozenUnderFog.Created(Actor self)
>    at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
>    at OpenRA.World.CreateActor(String name, TypeDictionary initDict)
>    at OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass2_0.<ResolveOrder>b__0(World w)
>    at OpenRA.World.Tick()
>    at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
>    at OpenRA.Game.LogicTick()
>    at OpenRA.Game.Loop()
>    at OpenRA.Game.Run()
>    at OpenRA.Program.Run(String[] args)
>    at OpenRA.Program.Main(String[] args)

**Comment by GraionDilach** [comment]
This is an upstream bug which was fixed in a later revision you're using atm.

**Comment by abcdefg30** [comment]
This was fixed in https://github.com/OpenRA/OpenRA/pull/10702. Thanks for the report, though!

**Comment by lbccjyx** [comment]
I've encountered this issue as well, and my solution is to switch to a different map.
