### ISSUE TITLE
Install from original CD [$5]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#124]
Installing from the original CD doesn't work, because Microsoft CAB isn't supported yet.

**Comment by jtyle6** [comment]
@Mailaender do you get? $5 if you close it?

**Comment by abcdefg30** [comment]
@pchote did the actual work. @Mailaender just merged the Pull Request.

**Comment by Mailaender** [comment]
Yep, @pchote please claim https://www.bountysource.com/issues/30699853-install-from-original-cd
