### ISSUE TITLE
Missing teleport/chronoshift [$5]

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#134]
Used by

- Chrono Miner
- Chrono Legionnaire

Chrono Miner in RA2:

![chronologic-ra2-cropped](https://cloud.githubusercontent.com/assets/3705231/13012572/82700144-d1b4-11e5-8418-6061c4d8d9bb.gif)

Chrono Miner in OpenRA (ra2 mod):

![chronologic-openra2-cropped](https://cloud.githubusercontent.com/assets/3705231/13012577/87161058-d1b4-11e5-9809-8b69e4078e96.gif)

Not sure if it's actually "missing" because it is used by Germany faction in RA mod.

**Comment by GraionDilach** [comment]
The Chrono Miner specific logic was written and submitted twice already (in #1 last) but due to various issues, haven't got merged yet.

CLeg teleport is on a to-do list.

**Comment by Fincer** [comment]
Ok, didn't notice that before. Thanks for pointing out. Also good to hear you have Chrono Legionnaire on the todo list.

Waiting for this teleport stuff to be merged.

**Comment by GraionDilach** [comment]
Personally the CLeg jump is quite simple to implement IMO so I guess I could look into it next weekend. I'd be happy though if @Mailaender and @abcdefg30 would decide beforehand if they intend to use the RA2 mod dll namespace at all.

**Comment by Mailaender** [comment]
We already have https://github.com/OpenRA/OpenRA/wiki/Traits#portablechrono which I planned to use for the Chrono Legionaire.

**Comment by GraionDilach** [comment]
CLeg doesn't even work that way though. An OpenRAesque way would be a similar hack like the CMiner implementation in #1, to have a trait which instantly move the unit to target positions, but also divide the passed distance with a trait-defined constant and apply upgrades for the resulting duration (which would apply the stopmove-transparent-enable-overlayblinkanim-stopattack upgrades in the particular CLeg).
