### ISSUE TITLE
Yuri mind control

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#144]
It has to change the owner while a connection is established and the controller isn't dead. http://modenc.renegadeprojects.com/MindControl has some insights.

**Comment by scshunt** [comment]
Talked this over with pchote today. He's of the opinion that it should wait until continuous-fire weapons are implemented.

**Comment by scshunt** [comment]
After more discussion including @GraionDilach and @pchote, I respectfully disagree with Paul and think that mind control should be implemented using specialized traits to track the mind control.

**Comment by MustaphaTR** [comment]
IIRC, @Phrohdoh was working on it even before we start to RA2 Mod.

**Comment by Mailaender** [comment]
I wrote some code https://github.com/Mailaender/ra2/pull/new/yuri that isn't completely finished. Not sure if I should finish it now. Don't want to run into a huge objection when submitting it.

**Comment by ibrokemypie** [comment]
+1
