### ISSUE TITLE
Tesla Reactor rendering issue

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#147]
I noticed this while I was playing as soviets today.

![teslagen_bug_openra](https://cloud.githubusercontent.com/assets/3705231/13231351/28f855e8-d9b2-11e5-919b-d2c9c7481de0.png)

As far as I can tell, only that specific corner of the building seems to be affected. At least I can't see any visually strange glitches occuring on the other corners of a Tesla Reactor.

**Comment by pchote** [comment]
Duplicate of #127, OpenRA/OpenRA#7520.

**Comment by Mailaender** [comment]
This doesn't happen anymore.
