### ISSUE TITLE
Unit ignores terrain geometry

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#150]
Don't ask me how's this possible but this happened to me on a map named as "tn03t8". Multiple times. The map is one of the original RA2 maps just converted to oramap format. 

![hoverharvester-openra2-faster](https://cloud.githubusercontent.com/assets/3705231/13233351/047352fe-d9bc-11e5-9b5a-a20ea52dcc23.gif)

Is this a
- map
- harvester
- pathfinding
- terrain tileset
- or terrain geometry bug? Or something strange happened on map conversion process? (didn't see anything strange though, and --check-yaml checks passed, too)

**Comment by Mailaender** [comment]
The tilesets are automatically imported so my best guess is that the original engine was a bit stricter and didn't count that as a pathable gap so the mapper was never punished for sloppiness.

**Comment by Fincer** [comment]
Okay. Thank you for quick responding.

I just tested this with other vehicles as well. Happened with them, too. Exactly same terrain spot. I used spawn "H" (middle left) as my starting point.

**Comment by GraionDilach** [comment]
No, this isn't a map bug. Apparently all such RA2 bottom cliffs are affected. I'm still figuring out why though, but this have happened with all my terrains I could've import in to OpenRA.

**Comment by WilliamWsyHK** [comment]
Actually I saw this one also in TS

**Comment by pchote** [comment]
> No, this isn't a map bug.

This specific situation does look like a map bug.  The tile that the chronominer drives over is a regular clear tile, and not part of the cliff.

**Comment by MustaphaTR** [comment]
This is indeed not a map bug. Problem is with tile. These E-W sliffs has problems in original YR too but not like that. Also possible reason of this is that passable tile in cliff.

![adsiz](https://cloud.githubusercontent.com/assets/7933210/13373201/654ecc92-dd69-11e5-8a2b-432b2ed0062d.png)

**Comment by Mailaender** [comment]
> happened to me on a map named as "tn03t8"

We don't ship that map so closing here. You can try investigating this further with the "Show Custom Terrain" debug command we recently added here.

**Comment by Mailaender** [comment]
Fixed by https://github.com/OpenRA/ra2/pull/540.
