### ISSUE TITLE
Aircraft carrier

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#151]
See http://modenc.renegadeprojects.com/Spawns and https://youtu.be/5J2j-NUcS4E

**Comment by MustaphaTR** [comment]
There is actually another issue for it. I think this can be closed as duplicate. #118

**Comment by GraionDilach** [comment]
That one is about missiles, not aircraft carrier. Yes, both are Spawns-derived in RA2, but that does not directly mean the two will be related in OpenRA.

**Comment by Mailaender** [comment]
There is also an upstream issue about it: https://github.com/OpenRA/OpenRA/issues/4157

**Comment by Mailaender** [comment]
Just saw that @forcecore already wrote `CarrierSlave` and `CarrierMaster` traits in his private fork.

**Comment by forcecore** [comment]
I have V3, too
https://www.youtube.com/watch?v=xTJNAAxUyU0 : if you watch closely, AA guns shoot down some of the missiles.

**Comment by Mailaender** [comment]
V3 is #118. Can you contribute your code?

**Comment by forcecore** [comment]
Indeed I would. However, it will take some time as the codes went through a major rewrite and need some stabilization.
