### ISSUE TITLE
wrong sound?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#152]
It is happend when I try to click any button in main menu

sound.log

Failed to parse WAV file umenucl1.wav. Error message:
System.OutOfMemoryException: Выдано исключение типа "System.OutOfMemoryException".
   в OpenRA.StreamExts.ReadBytes(Stream s, Int32 count) в d:\Games\OpenRA-bleed\OpenRA.Game\StreamExts.cs:строка 25
   в OpenRA.FileFormats.WavLoader.LoadSound(Stream s) в d:\Games\OpenRA-bleed\OpenRA.Game\FileFormats\WavLoader.cs:строка 82
   в OpenRA.FileFormats.WavLoader.TryParseSound(Stream stream, String fileName, Byte[]& rawData, Int32& channels, Int32& sampleBits, Int32& sampleRate) в d:\Games\OpenRA-bleed\OpenRA.Game\FileFormats\WavLoader.cs:строка 189

exception.log

Red Alert 2 Mod at Version {DEV_VERSION}
on map ba240d57ac307937bab3223ce71e0e37b84e3a9e (Blank by Matthias Mailänder).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: umenucl1.wav is not a valid sound file!
   в OpenRA.Sound.LoadSound(ISoundLoader[] loaders, IReadOnlyFileSystem fileSystem, String filename) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 71
   в OpenRA.Sound.<>c__DisplayClass1.<Initialize>b__0(String s) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 77
   в OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) в d:\Games\OpenRA-bleed\OpenRA.Game\Exts.cs:строка 131
   в OpenRA.Primitives.Cache`2.get_Item(T key) в d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\Cache.cs:строка 36
   в OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 364
   в OpenRA.Sound.PlayNotification(Ruleset rules, Player player, String type, String notification, String variant) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 379
   в OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 377
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Ui.HandleInput(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 91
   в OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 50
   в OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) в d:\Games\OpenRA-bleed\OpenRA.Game\Sync.cs:строка 183
   в OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 50
   в OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:строка 87
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:строка 354
   в OpenRA.Renderer.EndFrame(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Game\Renderer.cs:строка 157
   в OpenRA.Game.RenderTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 620
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 730
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 748
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 118
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 40

**Comment by abcdefg30** [comment]
Hm, I can' reproduce it somehow, are you using the latest version of both OpenRA and this repo?

**Comment by yaaaaa** [comment]
yes it is

**Comment by penev92** [comment]
What version (language-wise) of RA2 are you using? It is possible the files don't match those of the en-US version, which is probably what most of the devs are running, so there is a bogus file, or a file that the code can't handle.

**Comment by yaaaaa** [comment]
I use 7Wolf team localization MIX files.
[http://rutracker.org/forum/viewtopic.php?t=5180073](url)
Until recently, everything worked perfectly with this localization.

**Comment by yaaaaa** [comment]
How can I fix MIX file? umenucl1.wav must be in mix? what does this error mean?

**Comment by yaaaaa** [comment]
Just now, I redownload last OpenRA bleed and RA2 mod, and now it out of memory crash:

Red Alert 2 Mod at Version {DEV_VERSION}
on map 844106135f7993f089abf392d5371af5b0f002d7 (Blank by Matthias Mailänder).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Выдано исключение типа "System.OutOfMemoryException".
   в OpenRA.StreamExts.ReadBytes(Stream s, Int32 count) в d:\Games\OpenRA-bleed\OpenRA.Game\StreamExts.cs:строка 25
   в OpenRA.FileFormats.WavReader.LoadSound(Stream s) в d:\Games\OpenRA-bleed\OpenRA.Game\FileFormats\WavLoader.cs:строка 150
   в OpenRA.FileFormats.WavFormat.<>c__DisplayClass3.<.ctor>b__0() в d:\Games\OpenRA-bleed\OpenRA.Game\FileFormats\WavLoader.cs:строка 72
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в System.Lazy`1.get_Value()
   в OpenRA.FileFormats.WavFormat.GetPCMInputStream() в d:\Games\OpenRA-bleed\OpenRA.Game\FileFormats\WavLoader.cs:строка 56
   в OpenRA.Sound.LoadSound(ISoundLoader[] loaders, IReadOnlyFileSystem fileSystem, String filename) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 77
   в OpenRA.Sound.<>c__DisplayClass1.<Initialize>b__0(String s) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 87
   в OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) в d:\Games\OpenRA-bleed\OpenRA.Game\Exts.cs:строка 131
   в OpenRA.Primitives.Cache`2.get_Item(T key) в d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\Cache.cs:строка 36
   в OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 373
   в OpenRA.Sound.PlayNotification(Ruleset rules, Player player, String type, String notification, String variant) в d:\Games\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:строка 388
   в OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 377
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 368
   в OpenRA.Widgets.Ui.HandleInput(MouseInput mi) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 91
   в OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 50
   в OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) в d:\Games\OpenRA-bleed\OpenRA.Game\Sync.cs:строка 183
   в OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 50
   в OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:строка 87
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:строка 354
   в OpenRA.Renderer.EndFrame(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Game\Renderer.cs:строка 153
   в OpenRA.Game.RenderTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 583
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 693
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 711
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 118
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 40

**Comment by yaaaaa** [comment]
It is happening when I try to click any button in main menu

**Comment by abcdefg30** [comment]
Sorry, I don't think we can really help you there. :(

What happens when you replace `umenucl1` in [notifications.yaml](https://github.com/OpenRA/ra2/blob/99e0135629ec42405bddf806ec8e9140fb5172ab/audio/notifications.yaml#L144) by e.g. `uradaron`?

**Comment by yaaaaa** [comment]
Yes!! Its Work! Thank You Very Mutch!!

**Comment by GraionDilach** [comment]
`umenucl1` is likely to end up too short when IMA'd and corrupted due to it. I'm taking a guess here with the 7Wolf localization did IMA'd this sound, but yeah, IMA ADPCM encoding on less-than-around-half-second will have issues.

**Comment by GraionDilach** [comment]
On a second thought, throwing an `umenucl1.wav` file to `/bits/` should also fix this crash.

**Comment by yaaaaa** [comment]
Thank You! =)

**Comment by abcdefg30** [comment]
I think we're done here then. Nothing much we can do about that except suggestion workarounds.

**Comment by Icenowy** [comment]
@abcdefg30 I also met this problem. My mix files are the official Origin version (English).

**Comment by abcdefg30** [comment]
Hm, that is weird. Did you try renaming like I suggested in https://github.com/OpenRA/ra2/issues/152#issuecomment-204940757?

**Comment by Icenowy** [comment]
@abcdefg30 I did it and it's OK. It seems that the problem is caused by some umenucl1.wav shipped with Yuri's Revenge. Maybe the file have two official versions -- one OK, one broken. I have now a right version placed in bits/
