### ISSUE TITLE
Xbuild failing on ChronoResourceTeleport

### ISSUE THREAD

**Issue by jtyle6** [OpenRA/ra2#170]
Thing I have done, is moved ra2 mod out of Application Support into the openra folder in my documents.

[xbuild.txt](https://github.com/OpenRA/ra2/files/175096/xbuild.txt)

**Comment by abcdefg30** [comment]
Did you add the dependencies to [dependencies folder (OpenRA.Mods.RA2/dependencies)](https://github.com/OpenRA/ra2/tree/master/OpenRA.Mods.RA2/dependencies)?

**Comment by jtyle6** [comment]
Oops, didn't see that.  :(
