### ISSUE TITLE
System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by micro4jkl456** [OpenRA/ra2#175]
upon start after adding mix files as instructed. After hitting load the game crashes. 

DEBUG
Failed to initialize hardware cursors. Falling back to software cursors.
Error was: Failed to create hardware cursor `sell-blocked` - Failed to create cursor: CreateIconIndirect(): The parameter is incorrect.

Found 35 domains for movement class 699 on map Desert Shellmap.
Found 3 domains for movement class 4096 on map Desert Shellmap.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)
--Tick: 26 (local)
--Tick: 27 (local)
--Tick: 28 (net)
--Tick: 29 (local)
--Tick: 30 (local)
--Tick: 31 (net)
--Tick: 32 (local)
--Tick: 33 (local)
--Tick: 34 (net)
--Tick: 35 (local)
--Tick: 36 (local)
--Tick: 37 (net)
--Tick: 38 (local)
--Tick: 39 (local)
--Tick: 40 (net)
--Tick: 41 (local)
--Tick: 42 (local)
--Tick: 43 (net)
--Tick: 44 (local)
--Tick: 45 (local)
--Tick: 46 (net)
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'

EXCEPTION
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.ArgumentException`: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.ObjectCreator..ctor(Manifest manifest)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by Mailaender** [comment]
How did you name the folders where OpenRA and the RA2 mod is installed to?

**Comment by micro4jkl456** [comment]
D:\GOG Galaxy\OpenRA\mods\ra2

**Comment by Mailaender** [comment]
You are probably running an outdated version of OpenRA and it fails, because of the recent `mod.yaml` changes.

**Comment by micro4jkl456** [comment]
I will have to download the latest version and get back to you with the
results

**Comment by pedrus** [comment]
I have the same issue, downloaded the bleed version.

**Comment by Walkman100** [comment]
You could try [my RA2 install script](https://github.com/Walkman100/OpenRA-Install-Guide/blob/master/Install-RA2/InstallRA2.bat), it's windows only for now (I'm working on a linux one) and it doesn't do any error checking, but it `git checkout`s commits so it should always build exactly the same.

**Comment by pedrus** [comment]
It works now, thanks! Though the game crashes when I build a powerplant. But at least it runs now.

I guess the mod doesn't work with the last version of OpenRA anymore.

**Comment by Walkman100** [comment]
For the powerplant issue see #222 
I don't get what you mean by running the game with a command, I run `OpenRA.exe`, click on the Red Alert 2 Mod icon, then click <kbd>Load Mod</kbd>

**Comment by abcdefg30** [comment]
With that command the game would directly launch into the Red Alert 2 mod.

**Comment by pedrus** [comment]
I will retry but the game wouldn't run and would crash instantly if I didn't launch the executable with that command.

**Comment by abcdefg30** [comment]
Weird, I guess you had somehow a mod selected that crashes.

**Comment by Valkirie** [comment]
This one is easy to fix but the problem might be bigger.
My understanding is that openRA is unable to parse shorcuts like ra2| (.\mods\ra2\) and so on (/).

I was able to fix the issue by replacing shortcuts within mod.yaml. Fixed file below.
[mod.txt](https://github.com/OpenRA/ra2/files/344675/mod.txt)

Now it leads me back to the Crash on powerplant behaviour.
