### ISSUE TITLE
War factories don't open roofs for aircraft

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#182]
Nighthawk and Kirov are the examples.

**Comment by cookgreen** [comment]
Here is my idea: When War factory build aircraft finished, War Factory will be replaced by the War Factory which open roof, and set a time like 2 or 3 secs to trigger the War Factory become the original state after it open roof

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/pull/15303 providing a condition to trigger the open-roof animations with a duration synced with the aircraft flying up sounds like the simplest solution (it always flies up afterall, so jammed exits can't be an issue).
