### ISSUE TITLE
Mirage tanks don't stealth as trees

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#183]
http://cnc.wikia.com/wiki/Mirage_tank_(Red_Alert_2)

Fun fact: they used the manual disguise mechanic in the RA2 beta and Mental Omega http://modenc.renegadeprojects.com/Disguise

**Comment by GraionDilach** [comment]
Mental Omega doesn't use the manual disguising. Some mods did though.

The `DefaultMirageDisguises` list will be the tricky issue IMO, either we make a world trait which contains that list, either we cache the used-on-map tree types at unit creation. (Proper mapping always restated that list on the map to make sure the Mirage Tank picks a fitting tree, MO went with this).

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA/pull/11886 should help to make this.

**Comment by GraionDilach** [comment]
Not really. You're forgetting that upgrading the voxel art to sprite means even the owner/allies can't see that it's a Mirage Tank - since only decorations have stance visibility.

**Comment by MustaphaTR** [comment]
Well, current spy logic also doesn't have blinking while RA2 does. We can add a pip to them too. I'm not really a fan of blinking.

**Comment by Iamgoofball** [comment]
The blinking is pretty nice for knowing exactly what it looks like.
