### ISSUE TITLE
Add bridges support

### ISSUE THREAD

**Issue by Icenowy** [OpenRA/ra2#188]
When I'm trying import all the official maps of RA2, it seems that all the bridges are lost...

Some map became unplayable because of this

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/8916 and https://github.com/OpenRA/OpenRA/issues/8917.

**Comment by Mailaender** [comment]
There is even a prototype ready https://github.com/OpenRA/OpenRA/pull/10764 but it is blocked due to  a dispute.

**Comment by Icenowy** [comment]
@Mailaender thanks. Maybe I should do some research on OpenRA's code...

**Comment by Mailaender** [comment]
I made a new attempt: https://github.com/OpenRA/OpenRA/pull/11441.
