### ISSUE TITLE
GI not able to deploy

### ISSUE THREAD

**Issue by Elthan** [OpenRA/ra2#189]
GIs are not able to deploy like they can in the original game:

![ra2_gi](https://cloud.githubusercontent.com/assets/7212361/14570578/57cc58da-0345-11e6-9bf6-aa5472e77e23.PNG)

**Comment by GraionDilach** [comment]
Yeah, it seems troublesome at this stage.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/ra2/pull/168 for a failed attempt.

**Comment by Elthan** [comment]
I see. Is the idea to only do it with editing the YAML file or is it possible to (f.ex.) create a custom upgrade to do it?

**Comment by Phrohdoh** [comment]
Upgrades via yaml.

**Comment by ibrokemypie** [comment]
+1

**Comment by forcecore** [comment]
With condition system, I think this is becoming possible.
Since GIs will have deployed and undeployed WithInfantryBody, then only WithMakeAnimation needs to be used, as thumper does, hopefully.

https://github.com/OpenRA/OpenRA/pull/13737

**Comment by GraionDilach** [comment]
The main problem here is multiple turrets support or something along the way. TakeCover uses a turret and the deployed GI should also be a "turret".

**Comment by forcecore** [comment]
Oh yeah I remember, it's been ages ago since I implemented fire ant.

**Comment by Mailaender** [comment]
I made a new attempt https://github.com/OpenRA/ra2/pull/394 to find out the actual status of the feature.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/ra2/pull/547
