### ISSUE TITLE
Crash after press a "P" key

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#194]
Red Alert 2 Mod at Version {DEV_VERSION}
on map 7c8e7a330adc911200225027aa2ce111971fe629 (Tsunami by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: Cannot find widget with Id `INGAME_DIPLOMACY_BG`
   в OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\WidgetLoader.cs:строка 42
   в OpenRA.Game.LoadWidget(World world, String id, Widget parent, WidgetArgs args) в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 127
   в OpenRA.Mods.Common.Widgets.Logic.MenuButtonsChromeLogic.OpenMenuPanel(MenuButtonWidget button, WidgetArgs widgetArgs)
   в OpenRA.Mods.Common.Widgets.Logic.MenuButtonsChromeLogic.<>c__DisplayClass19.<.ctor>b__8()
   в OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__e(KeyInput _)
   в OpenRA.Mods.Common.Widgets.ButtonWidget.HandleKeyPress(KeyInput e)
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 393
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Widget.HandleKeyPressOuter(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 389
   в OpenRA.Widgets.Ui.HandleKeyPress(KeyInput e) в d:\Games\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:строка 120
   в OpenRA.DefaultInputHandler.<>c__DisplayClass1.<OnKeyInput>b__0() в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 40
   в OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) в d:\Games\OpenRA-bleed\OpenRA.Game\Sync.cs:строка 183
   в OpenRA.DefaultInputHandler.OnKeyInput(KeyInput input) в d:\Games\OpenRA-bleed\OpenRA.Game\Input\InputHandler.cs:строка 40
   в OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2Input.cs:строка 165
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Platforms.Default\Sdl2GraphicsDevice.cs:строка 354
   в OpenRA.Renderer.EndFrame(IInputHandler inputHandler) в d:\Games\OpenRA-bleed\OpenRA.Game\Renderer.cs:строка 153
   в OpenRA.Game.RenderTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 583
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 693
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 711
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 118
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 40

**Comment by MustaphaTR** [comment]
Which version of OpenRA you put RA2 mod on? Fraigle Diplomacy has removed recently.

**Comment by abcdefg30** [comment]
> Which version of OpenRA you put RA2 mod on? Fraigle Alliances has removed recently.

Seems like I forgot to remove the diplomacy button, filed #195 to fix this.
