### ISSUE TITLE
"Install mod" still showing

### ISSUE THREAD

**Issue by WACMemphis** [OpenRA/ra2#205]
I followed the instructions and I still see the "Install mod" button when selecting the RA2 mod.
I can't say why that is because I've got all the files that the wiki lists as required:

![Image](http://i.imgur.com/KnMq3Ot.png)

Does anyone have an idea what's wrong?

When I click it I get a "Missing dependencies" message:

"Please fully install the following mods then try again: modchooser ({DEV_VERSION})"

**Comment by Mailaender** [comment]
> "Please fully install the following mods then try again: modchooser ({DEV_VERSION})"

The mod only works with the latest development version of the OpenRA engine. You need to compile it yourself.

**Comment by jtyle6** [comment]
It can be done with: https://github.com/OpenRA/ra2/wiki/Step-by-Step

**Comment by WACMemphis** [comment]
@Mailaender Right, apologies, I must have missed that.
@jtyle6 Thanks
