### ISSUE TITLE
Repository layout doesn't allow releases

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#208]
I made some tests and the OpenRA.Mods.RA2.DLLs created cause `TypeLoadExceptions` when used with regular released versions of OpenRA or thirdparty mods.

I assume the hard-coded https://github.com/OpenRA/ra2/tree/master/OpenRA.Mods.RA2/dependencies location is the root of all evil.

It also copies unrelated OpenRA.Game.exe and OpenRA.Mods.*.dll files into the mod root, which isn't wanted behavior.

Also the https://github.com/OpenRA/ra2/wiki/Step-by-Step setup is ridiculously complicated.

**Comment by GraionDilach** [comment]
Either this, either splitting the repository into a ra2-mod and a ra2-dll repository, which can be checked out into the OpenRA and OpenRA/mods folder directly. To fully support such a setup though, one might need to have an additional commit in OpenRA to expand .gitignore to prevent conflicts within the git repos (The same commit can also be used to expand upstream makefiles).

Noidea how well it would ease up producing releases though (tbh until the TS dll is missing from the releases, the discussion around it is IMO moot).

Attacque Supérior and Shattered Paradise already follows this above concept (SP is a better example, because in SP, the mod is indeed in a third git repository, while AS only has the DLL repo set up.) Look at @ABrandau to see how it's done.

**Comment by Mailaender** [comment]
> splitting the repository into a ra2-mod and a ra2-dll repository

Has the downside that both need to be kept in sync and it then needs at least two (three if it also requires an OpenRA upstream change) pull requests even for tiny feature additions.

**Comment by GraionDilach** [comment]
Gitignoring their folders would only need to be done once. Otherwise yes, I know, there isn't a perfect solution.

**Comment by Mailaender** [comment]
Moving the trait logic where it belongs https://github.com/OpenRA/OpenRA/pull/11301 seems to be the only sane way until the libraries can be installed into GAC or distributed via NuGet.

**Comment by Mailaender** [comment]
I followed your suggestions and separated mod logic https://github.com/OpenRA2/Mods.RA2 from the mod ruleset https://github.com/OpenRA2/ra2 The benefit over this repository is that I preserved all commits from previous contributors including:

* https://github.com/Phrohdoh/oramod-ra2
* https://github.com/Phrohdoh/OpenRA/tree/ra2%23master

Now building is a simple matter of cloning https://github.com/OpenRA2/OpenRA building OpenRA as usual and it won't break as easily as we have to pull in the commits from OpenRA upstream into the develop branch first.

**Comment by Mailaender** [comment]
After the harsh criticism from https://github.com/OpenRA/OpenRA/issues/11301 I split everything into it's own umbrella project: https://github.com/OpenRA2 Ping me if you are interested in contributing.

**Comment by GraionDilach** [comment]
On the other hand, a followup of #209 could probably let us do releases in oramod format. I'm sorry for your lost efforts some days ago, though.

**Comment by Mailaender** [comment]
We will still want to migrate to https://github.com/OpenRA2/ra2 as this repository does not include the full commit list and therefore does not credit contributors correctly.

**Comment by GraionDilach** [comment]
Forcepush it over then IMO.

**Comment by Mailaender** [comment]
Okay done.

**Comment by abcdefg30** [comment]
GG

**Comment by scshunt** [comment]
What is our status right now? I'm very confused and feel like I missed something somewhere. Are we all happy and still working from this project?

**Comment by abcdefg30** [comment]
> What is our status right now? I'm very confused and feel like I missed something somewhere. Are we all happy and still working from this project?

Good questions. And I don't really know the answers as well...
I guess you get a clear no from me regarding the last one though.

**Comment by Mailaender** [comment]
I added all past https://github.com/OpenRA2/ra2/graphs/contributors which took me a lot of efforts.

**Comment by abcdefg30** [comment]
I'm still not all convinced that https://github.com/OpenRA2/OpenRA is a good idea and think this force pushing was a bit premature. Why did you need to at all anyway? You could have restored the past commits locally as well I think.

**Comment by GraionDilach** [comment]
I am working on this. Dunno who else. The discussion happened on Monday and the followup in the GraionDilach:infrastructure-pchote branch were made to make sure this repository will be kept as active.

It appears we lost WithSwimSuits.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/ra2/blob/master/OpenRA.Mods.RA2/Traits/Render/WithSwimSuit.cs should be there. It just took me a few attempts. I agree that doing the rewrite at this stage is far from ideal, but it wasn't done properly in the first place so there was no other chance. The repository history in https://github.com/OpenRA2 is a bit cleaner, but as you guys don't want a regular mod hierarchy and prefer this rather thirdparty mod hack attempt, at least the history of this mod is now imported.

**Comment by GraionDilach** [comment]
Yer, I missed the `Render` directory.

In any case, give me 30 minutes to restore `GraionDilach:infrastructure-pchote` directory which should be the longterm solution to all our issues with stuff. Okay, I only got to the point where upstream issues kicked in but it should give you guys an idea for the future.

**Comment by GraionDilach** [comment]
@abcdefg30 and @scshunt The aim with #212 (after the upstream issues are resolved) to use the main directory as a support directory which has an OpenRA bleed folder inside.

This should allow us to replace our make scripts with ones which can checkout an exact git commit of OpenRA into root/OpenRA, where it would run `make dependencies && make all && make version` then build the RA2 project. For a release, we could then just simply zip down the `mods` folder and change the extension.

**Comment by abcdefg30** [comment]
I still didn't get why we have to turn this into a Support directory then.

**Comment by GraionDilach** [comment]
Because we can't turn it to anything else without hacking or terrible workarounds - something so far all iterations of the project suffered from. The current setup is messy and requires quite an effort to be automated. If we turn it to the mods directory or keep it as ra2, then that means we cannot assume where our dependencies are and we can only work with static libraries as well.

This might look untidy at first but it would simplify all our issues against upstream. That's a compromise which IMO well worths it.

**Comment by Mailaender** [comment]
It still is a terrible hacky workaround, but it is the only way @pchote allows for. Let's see if it brings any improvements. Keeping the most anticipated mod out of the main project that is nowhere near modular to enough to sustain thirdparty development was the worsed wrong decision so far, but we are at a stage where it gets repeated religiously so we have to deal with it somehow.

**Comment by scshunt** [comment]
I tend to agree with @pchote's end goal here. Let's hope we can get away from hackiness in the future.

**Comment by scshunt** [comment]
Also, can we perhaps include OpenRA as a subtree? That seems like the ideal way.

**Comment by Mailaender** [comment]
I read about that and gave it a try https://github.com/OpenRA2/Aggregator but git subtree is confusing at least to me, because it mixes two repositories with no clear separation. Using sub modules like in https://github.com/OpenRA2/OpenRA at least makes the origins of the source code and where to contribute more visible.

**Comment by GraionDilach** [comment]
>I read about that and gave it a try https://github.com/OpenRA2/Aggregator but git subtree is confusing at least to me, because it mixes two repositories with no clear separation.

Another reason why the support directory way is the way to go, no chance for confusion.

The upstream commits can also be guaranteed to be compatible via the mod dependency. As https://github.com/OpenRA/OpenRA/pull/11301#issuecomment-219537259 explains, we can use `ra2.yaml`'s `RequiresMods: modchooser: git-(version)` to check out exact versions of upstream. This resolves the need to keep around a submodule on the cost of the makefiles will necessary run `make version` as part of the OpenRA compilation.

I'm aware my branch is still incomplete, but check it out, check out a bleed version into the OpenRA folder and open the solution. Manually compiling the RA2 project already gives us the same automation upsteam's mod dll compilations do.

**Comment by abcdefg30** [comment]
I made good experiences with using submodules in the past with https://github.com/Phrohdoh/oramod-ra2 .

> The upstream commits can also be guaranteed to be compatible via the mod dependency. As OpenRA/OpenRA#11301 (comment) explains, we can use  ra2.yaml 's  RequiresMods: modchooser: git-(version)  to check out exact versions of upstream. This resolves the need to keep around a submodule on the cost of the makefiles will necessary run  make version  as part of the OpenRA compilation.

Shouldn't be needed when we use a submodule. It seems like everyone is insisting on creating an OpenRA subdirectory anyway, so I'd vote for a submodule as the required OpenRA version is set in the submodule and can easily be fetched and the handling isn't difficult as well, just `cd` into the submodule with your "git bash" and work in there as it was a normal repository.

**Comment by Mailaender** [comment]
https://github.com/OpenRA2 has the benefit that we automatically keep stable all the time until we update the submodule commits so things like https://github.com/OpenRA/ra2/issues/217 won't happen anymore.

Another thing to consider: if we ever merge this mod with OpenRA mainline, we will want each folder in a different repository. Merging this repo will cause a mess. https://github.com/OpenRA2/ra2 and https://github.com/OpenRA2/Mods.RA2 will fit in smoothly without conflicts.

**Comment by abcdefg30** [comment]
This is what I have for now btw: https://github.com/OpenRA/ra2/compare/master...abcdefg30:layout
It would work, but the `version` command is still WIP.

**Comment by abcdefg30** [comment]
Fixed by #386 hopefully.
