### ISSUE TITLE
Scroll Buttons located completely wrong

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ra2#21]
![scroll buttons](https://cloud.githubusercontent.com/assets/7933210/12220960/9e019632-b78f-11e5-9746-2127ede6f545.png)

**Comment by x-a-n-a-x** [comment]
I haven't been able to reproduce this bug. I guess you tested an old version of the interface, didn't you?

Could you try this branch : https://github.com/x-a-n-a-x/ra2/tree/RA2_without_powerdown_nor_diplomacy and tell me if it still happens? Thanks.

**Comment by MustaphaTR** [comment]
I tried this on bleed and https://github.com/x-a-n-a-x/ra2/tree/RA2_soviets_productionbuttons_fixed and still happens there. I'm currently tring https://github.com/x-a-n-a-x/ra2/tree/RA2_without_powerdown_nor_diplomacy

**Comment by x-a-n-a-x** [comment]
Can somebody else reproduce this bug with https://github.com/x-a-n-a-x/ra2/tree/RA2_soviets_productionbuttons_fixed ?

**Comment by MustaphaTR** [comment]
You need to add some civilian buildings to this. There is not enough building to show scroll button in bleed.
	Buildable:
		Queue: Building
		BuildPaletteOrder: 1000
		Prerequisites: ~disabled

**Comment by x-a-n-a-x** [comment]
So you're saying that you modified my branch, in order to be able to notice this bug ?

**Comment by abcdefg30** [comment]
I could reproduce this exactly when resizing the window (windowed mode).
I think that is rather an OpenRA bug than a RA2 specific thing.
![ra2menuglitch](https://cloud.githubusercontent.com/assets/7704140/17086342/ab906e40-51ef-11e6-9d64-c2a834960e23.png)
