### ISSUE TITLE
Can't execute "dependencies" in make.cmd

### ISSUE THREAD

**Issue by Grantelbart4** [OpenRA/ra2#214]
I tried to follow the guide on how to install the ra2 mod, but when I type in "dependencies" in the make.cmd console I get this:
![fehler](https://cloud.githubusercontent.com/assets/19558564/15530107/37c538d2-2207-11e6-9302-bfebb7c11273.PNG)
The german text means: 
Test-Path : The argument can't be bount to the parameter "Path" because it is NULL.
At C:\Users\Fulgur\Documents\Openra\mods\ra2\make.ps1:71 Characters:17

Does anybody know what the problem could be?

**Comment by GraionDilach** [comment]
Duplicate, sorry.

**Comment by abcdefg30** [comment]
Duplicate of #213 to be exact.
