### ISSUE TITLE
Crash after training a unit

### ISSUE THREAD

**Issue by Grantelbart4** [OpenRA/ra2#216]
I must be really getting on your nerves now :/ When I train a conscript the game crashes with the message:

> Failed to initialize hardware cursors. Falling back to software cursors.
> Error was: Failed to create hardware cursor `harvest` - Failed to create cursor: CreateIconIndirect(): Falscher Parameter.
> 
> Voxel sheet overflow! Generating new sheet
> Found 2 domains for movement class 493 on map Blank.
> Found 1 domains for movement class 512 on map Blank.
> Found 2 domains for movement class 1005 on map Blank.

Afterwards I only get a lot of "--Tick" lines. I guess it has something to do with the graphics

**Comment by GraionDilach** [comment]
These are all fine. What made you crash was an accidental bug introduced some days ago in the OpenRA engine, which got fixed as part of https://github.com/OpenRA/OpenRA/pull/11356. You have to unfortunately get a new bleed version of OpenRA and recompile (RA2 itself isn't needed to be recompiled though).

**Comment by Grantelbart4** [comment]
Thanks for the help. Everything works perfect now. Sorry for the trouble I caused :P Anyways, I will modifie the game and if there is something missing in your mod I will send you the needed things
