### ISSUE TITLE
Idea on how to fix the Kirov

### ISSUE THREAD

**Issue by Grantelbart4** [OpenRA/ra2#226]
I was thinking of merging a unit with the kirov (kind of like a turret). Only the Kirov would be visible while the second "merged" unit will be invisible. The Kirov will not have an attack, but it will head towards other units (with an attack range of 0). The merged unit will fire when units are in the range of 1 field. 
The only problem is that I don't know which code would be needed and I have no idea if it is possible to merge units.

**Comment by GraionDilach** [comment]
What is the bug with the Kirov, actually?

**Comment by Grantelbart4** [comment]
The kirov does not fly over the building to bombard it. Instead it simply drops the bomb far away from the target and deals much less damage or doesn't damage the target at all. 
I don't know how to record an animation so I will jsut post a screenshot.
![kirov](https://cloud.githubusercontent.com/assets/19558564/15785544/9e51f588-296c-11e6-8e41-b51dad01af42.png)

**Comment by alercah** [comment]
It seems to me that a pseudounit is wrong and the Kirov may need a custom trait to handle the movement.

**Comment by cookgreen** [comment]
The reason why Kirov went wrong, because Kirov's type is Aircraft which means Kirov will behave like Aircraft in OpenRA
The Aircraft in OpenRA will attack the enemy unit out of the cell
One way is to make a new trait to suit the Kirov, Another way is to make Kirov as AttackHeli not Aircraft

**Comment by cookgreen** [comment]
#12674

**Comment by cookgreen** [comment]
https://github.com/OpenRA/OpenRA/issues/12674

**Comment by cookgreen** [comment]
Update:I have tried to fix that , but seems failed. I have added the AttackHeli to the Kirov, but it still attack out of the range rather than fly towards the target

**Comment by Mailaender** [comment]
Improved in https://github.com/OpenRA/ra2/pull/538.
