### ISSUE TITLE
Crash in startup mod

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#238]
Just trying to start new RA2 mod version in new OpenRA bleed

[Logs.zip](https://github.com/OpenRA/ra2/files/321760/Logs.zip)

**Comment by abcdefg30** [comment]
Looks like the same error as #175.

**Comment by yaaaaa** [comment]
install-RA2.bat script from Walkman100 did not help to me(
Map format 10 is not supported??

**Comment by GraionDilach** [comment]
We're at map format 11 so yes.

**Comment by yaaaaa** [comment]
I need to convert 1.oramap to map format 11?

**Comment by abcdefg30** [comment]
Yeah, maps with an invalid map format can cause crashes.

**Comment by yaaaaa** [comment]
where can i found 1.oramap file?

**Comment by abcdefg30** [comment]
It's not a shipped map, so probably in your custom maps folder: https://github.com/OpenRA/OpenRA/wiki/Mapping#location

**Comment by yaaaaa** [comment]
Intresting, it was in custom map folder in (...OpenRA\maps\ra\{DEV_VERSION}).
Anyway Crash isn't gone:
[Logs.zip](https://github.com/OpenRA/ra2/files/322364/Logs.zip)

**Comment by yaaaaa** [comment]
https://github.com/OpenRA/ra2/issues/175#issuecomment-230115947
this is help to start mod
