### ISSUE TITLE
PowerShell Error

### ISSUE THREAD

**Issue by zerogott** [OpenRA/ra2#239]
Hey,
i downloaded the latest master,and the latest openRA bleed,after typing dependencies in the ra2 PowerShell i just get https://i.gyazo.com/5f07a480e473709ddd9ccb6ad71f1dba.png

and info on it?

**Comment by abcdefg30** [comment]
Ah yeah, someone broke the shell within the last weeks. You should be able to bypass the issue by giving the path directly, i.e. just type in "dependencies \<path>" directly. (\<path> is the path to your OpenRA install.)

**Comment by Walkman100** [comment]
https://github.com/OpenRA/ra2/pull/211#issuecomment-221999129

We should either figure out how to fix it (I know nothing about PowerShell scripts) or, if that method is going to be made obsolete by a better repo design anyway, update the wiki page for now.

**Comment by Mailaender** [comment]
As no one came up with a fix I reverted the breaking change https://github.com/OpenRA/ra2/issues/248.

**Comment by thefloe1** [comment]
I guess changing line 63 from
`if ($args.Length -eq 1)`
to
`if ($args.Length -lt 1)`

should do the trick.

**Comment by Mailaender** [comment]
Send a pull request, please.

**Comment by Phrohdoh** [comment]
@Mailaender You already have a PR open that can fix that.

**Comment by Mailaender** [comment]
Closed my pull request. As mentioned above, I just clicked the revert button.

**Comment by Phrohdoh** [comment]
Could a Windows user test #256 please?

**Comment by Phrohdoh** [comment]
Closed via #256.
