### ISSUE TITLE
port old ra2 maps to openra2

### ISSUE THREAD

**Issue by fastfading** [OpenRA/ra2#244]
there are only 9 maps in ra2 mod
how can I port the other old map (ra2 map and yuri map ) to openra2 format.
Is there any tools?  If yes, how to use it?

**Comment by Mailaender** [comment]
Use the command line tool: `OpenRA.Utility.exe ra2 --import-ts-map`

**Comment by fastfading** [comment]
I have did what you told , however I got such errors. 
Ignoring unknown actor type: `inyelwlamp`
Ignoring unknown actor type: `inyelwlamp`
Ignoring unknown actor type: `inyelwlamp`
Ignoring unknown actor type: `inyelwlamp`
Ignoring unknown actor type: `ingrnlmp`
Ignoring unknown actor type: `ingrnlmp`
Ignoring unknown actor type: `inredlmp`
Ignoring unknown actor type: `inredlmp`
Ignoring unknown actor type: `inredlmp`
Ignoring unknown actor type: `inredlmp`
Ignoring unknown actor type: `inpurplamp`
18,43 unknown overlay 25
18,44 unknown overlay 25
40,79 unknown overlay 25
Ignoring unknown lighting type: `Level`
Ignoring unknown lighting type: `Ground`
Ignoring unknown lighting type: `IonRed`
Ignoring unknown lighting type: `IonBlue`
Ignoring unknown lighting type: `IonGreen`
Ignoring unknown lighting type: `IonLevel`
Ignoring unknown lighting type: `IonGround`
Ignoring unknown lighting type: `IonAmbient`

It seem the changed map is much smaller than the origin one.
-rwxr-xr-x@ 1 staff  staff   66389 May  8  2006 tianya21.mpr
-rw-------  1 staff  staff    4488 Jun 27 09:32 tianya21.oramap
-rwxr-xr-x@ 1 staff  staff  247303 May  8  2006 tianya23.mpr
-rw-------  1 staff  staff   35535 Jun 27 09:33 tianya23.oramap

How should I use this maps? which folder should I put it in ?

**Comment by fastfading** [comment]
Hi Matthias

I have did what you told , however I got such errors.
Ignoring unknown actor type: inyelwlamp
Ignoring unknown actor type: inyelwlamp
Ignoring unknown actor type: inyelwlamp
Ignoring unknown actor type: inyelwlamp
Ignoring unknown actor type: ingrnlmp
Ignoring unknown actor type: ingrnlmp
Ignoring unknown actor type: inredlmp
Ignoring unknown actor type: inredlmp
Ignoring unknown actor type: inredlmp
Ignoring unknown actor type: inredlmp
Ignoring unknown actor type: inpurplamp
18,43 unknown overlay 25
18,44 unknown overlay 25
40,79 unknown overlay 25
Ignoring unknown lighting type: Level
Ignoring unknown lighting type: Ground
Ignoring unknown lighting type: IonRed
Ignoring unknown lighting type: IonBlue
Ignoring unknown lighting type: IonGreen
Ignoring unknown lighting type: IonLevel
Ignoring unknown lighting type: IonGround
Ignoring unknown lighting type: IonAmbient

It seem the changed map is much smaller than the origin one.
-rwxr-xr-x@ 1 staff staff 66389 May 8 2006 tianya21.mpr
-rw------- 1 staff staff 4488 Jun 27 09:32 tianya21.oramap
-rwxr-xr-x@ 1 staff staff 247303 May 8 2006 tianya23.mpr
-rw------- 1 staff staff 35535 Jun 27 09:33 tianya23.oramap

How should I use this maps? which folder should I put it in ?

There are many player made custom map online .

We could use other maps that don't contain bridge.


And I have a question , that is all 3d object not supported?

such as v3 rocket ,  Dreadnought， bridge

And will it support yuri revenge unit later?


Looking forward to your reply.

Best Regards

Hui

2016-06-25 23:23 GMT+08:00 Matthias Mailänder <notifications@github.com>:

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/3605, https://github.com/OpenRA/OpenRA/issues/8916 and https://github.com/OpenRA/OpenRA/issues/8917 aren't supported yet. Same goes for https://github.com/OpenRA/OpenRA/issues/7673. Place the map at the directories described at https://github.com/OpenRA/OpenRA/wiki/Mapping#location in the `ra2` folder. You can also already upload your conversions at http://resource.openra.net/
