### ISSUE TITLE
Win: cannot start game

### ISSUE THREAD

**Issue by thefloe1** [OpenRA/ra2#247]
Hi,

I followed the step-by-step instructions on the Wiki, but when starting the game it crashes with:
`Red Alert Mod at Version git-
on map 7b09dbae8ac1615ea049c04748bc66e319cf84ef (Desert Shellmap by Scott_NZ).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `OpenRA.YamlException`: ActorInfo("brik") failed to initialize because of the following:
Missing:
OpenRA.Mods.Common.Traits.FrozenUnderFogInfo 
Unresolved:
OpenRA.Mods.RA.Traits.FrozenUnderFogUpdatedByGpsInfo: { OpenRA.Mods.Common.Traits.FrozenUnderFogInfo }

   at OpenRA.ActorInfo.TraitsInConstructOrder()
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr)
   at OpenRA.World.LoadComplete(WorldRenderer wr)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
`

How can I fix this?

**Comment by Phrohdoh** [comment]
`Desert Shellmap by Scott_NZ` is not a RA2 map nor is `brik` an RA2 actor.
This belongs in OpenRA proper, if it still happens.
I cannot reproduce this on OpenRA/OpenRA@921375973eff6b650a69ea8524fa13c241aad820.

**Comment by thefloe1** [comment]
Thanks for clarifying this. But when just building OpenRA everything works fine. I get this error after building the RA2 mod. OpenRA/OpenRA@9213759 and OpenRA/ra2@6d1c36d.

**Comment by Phrohdoh** [comment]
You built OpenRA and ran RA and it worked, then built and ran RA2 and got this crash, correct?

**Comment by thefloe1** [comment]
right

**Comment by Phrohdoh** [comment]
`Red Alert Mod at Version git-` is a bit odd.
Did you at one time run `make version`?
It looks like it barfed and didn't append the short sha to the version string.

I am unable to reproduce this in any way.
Would you mind starting completely from scratch?

Make sure to get the latest commit of OpenRA and RA2, build OpenRA, copy the necessary files to `OpenRA.Mods.RA2/dependencies`, build RA2, and try again?

**Comment by thefloe1** [comment]
this happens when downloading the repository as  a ZIP archive.

When running make version it tells: 
`fatal: Not a git repository (or any of the parent directories): .git
Version strings set to 'git-'.`

**Comment by thefloe1** [comment]
I cloned the repositories, made make dependencies, make version and make all on OpenRA and den dependencies and all on RA2. Copied ra2 to Documents/RA2/mods and copied the dlls from dependencies into the main OpenRA folder.

At first everything starts, and I can select the mods.
When I select RA2 (after installing the content from CD) I get a window telling: "Please fully install the following mods: modchooser ({DEV_VERSION}).

When I then try to run RA, I get the exception above.
Now, everytime when starting the game, I get that exception stated in first post.

**Comment by GraionDilach** [comment]
Run OpenRA `make version {DEV_VERSION}`. `make version` does not generate a hash with the zip download, since the zip download isn't a git repository, just a zipped folder status.

**Comment by abcdefg30** [comment]
> Copied ra2 to Documents/RA2/mods

You probably want `Documents/OpenRA/mods`.

> copied the dlls from dependencies into the main OpenRA folder.

You shouldn't need to copy the dependencies in there, as they're actually taken from there by the `dependencies` command. (Assuming you mean the dev install with "main OpenRA folder", as this mod is not supposed to be run on a release or playtest version.)

> I get a window telling: "Please fully install the following mods: modchooser ({DEV_VERSION}).

See what @GraionDilach just wrote before I could press the `Comment` button. :p

**Comment by thefloe1** [comment]
So the instructions in  the wiki are not up to date: [Step-by-Step](https://github.com/OpenRA/ra2/wiki/Step-by-Step)^?

**Comment by abcdefg30** [comment]
> So now it's working. 

Ok, good to hear. Sorry for the hassle, this is an "unstable" developer version after all, though.
