### ISSUE TITLE
Preset enemy on *.oramap don't attack and with no ai

### ISSUE THREAD

**Issue by fastfading** [OpenRA/ra2#269]
Preset enemy on *.orimap don't attack and with no ai
The are just decoration.
Some maps are created with neutral enemies.
And some maps are designed as campaign ,   
there are preset enemies.

And they do not function.

**Comment by Mailaender** [comment]
Can you upload the affected .oramaps at http://resource.openra.net/?

**Comment by fastfading** [comment]
[redmap72.zip](https://github.com/OpenRA/ra2/files/345654/redmap72.zip)

There are plenty of map suit my case.

**Comment by Mailaender** [comment]
Extract the maps with unzip and change

```yaml
		Owner: Neutral
```

to

```yaml
		Owner: Creep
```

**Comment by fastfading** [comment]
Is there any doc for yaml configuration?
Can I edit owner in map editor? How?
For some campaign maps ,  some actor on map are my troop, some are friendly
unit, some are enemy.
How can I configure this?

2016-07-04 14:01 GMT+08:00 Matthias Mailänder <notifications@github.com>:

**Comment by Mailaender** [comment]
Have a look at https://github.com/OpenRA/OpenRA/wiki/Mapping
The owner can only be edited in the map editor by removing and re-adding the actor with the new owner.
Have a look at the existing campaign maps: https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/maps to see how to setup enemies and friendlies.
