### ISSUE TITLE
cathosp is missing

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#270]
It looks like the original game is differentiating between civilian hospital and tech hospital: https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L10548

**Comment by MustaphaTR** [comment]
Do we need it. I don't think so.  I think only its name is different(i can't check the rules now,  my browser has problems with big files) and some maps uses so its unexistance cause problems at importing. Nothing else.

**Comment by GraionDilach** [comment]
Merge them in the importer. One of these were unused.

**Comment by Mailaender** [comment]
https://www.diffchecker.com/9cbnazh8 they are indeed similar. Explosion effects seems to be the only difference. I thought one was decorational and the other functional.

**Comment by Phrohdoh** [comment]
It is possible that someone wrote custom rules in their maps for the unused hospital type.
By merging them without care you'd be punishing them.

This may not be an issue in practice but it should be considered.
