### ISSUE TITLE
Question:  Can I import mission map from utilities?

### ISSUE THREAD

**Issue by fastfading** [OpenRA/ra2#277]
Can I import mission map from utilities?  How?

If not ,  is there any plan to add mission map just like openra1

**Comment by fastfading** [comment]
I try load the mission map .
The terrain and unit set on the terrain is right.
But units are all set as netrual , with no ai logic. I set them as creeps it attach everyone.
My expectation is that in mission map ,  enemy are there at beginning, and do not need spawn point.
They will attack as the mission plan.
And One more thing , in origin game it seems could set it as auto repair for players ,   and   enemy ai will reconstruct defend towers if they are destroyed.

**Comment by GraionDilach** [comment]
Mission scripts will probably never get a converter due to reasons.

**Comment by abcdefg30** [comment]
Yeah, unfortunately you will have to code everything from scratch using Lua, as we can't import the original scripts.

**Comment by MustaphaTR** [comment]
I think that would be good to let map importer import sides and edited code.

**Comment by fastfading** [comment]
But how  ra1  mission works?


2016-07-13 23:54 GMT+08:00 abcdefg30 <notifications@github.com>:

**Comment by GraionDilach** [comment]
RA1 missions are rescripted by people from scratch.

**Comment by Mailaender** [comment]
Some students tried to create trigger to Lua converters: https://scm.thm.de/redmine/projects/dtdj-ultj/wiki/Automatische_Generierung_von_Karten but they never submitted their conversion tools.
