### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by QueenObama** [OpenRA/ra2#281]
Whenever I launch the game from the .exe given inside the OpenRA-Bleed folder, it flashes for a second and then crashes immediately. I even moved the OpenRA.Mods.RA2.dll file to the ra2 folder, and its still crashing.

Whats weird to me is I can still launch the game just fine from the OpenRA folder in my documents, but I can't play the RA2 mod from there.

**Comment by GraionDilach** [comment]
Logs?

**Comment by QueenObama** [comment]
[Logs.zip](https://github.com/OpenRA/ra2/files/379863/Logs.zip)
