### ISSUE TITLE
Implement installation script / wizard

### ISSUE THREAD

**Issue by testman42** [OpenRA/ra2#286]
Would it be possible to make a script that installs dependencies needed for compilation and guides user trough installation of this mod?

**Comment by Walkman100** [comment]
There are a few user-made ones, but it would be really nice to have one in the repo

**Comment by Mailaender** [comment]
See https://github.com/Fincer/openra-tibsunra2 but the better way would be to make the mod installation less complicated in general.

**Comment by MichelKansou** [comment]
I will try to make one for OSX first for fun ^^

**Comment by MichelKansou** [comment]
I have just finished my first [wizard](https://github.com/MichelKansou/OpenRA-MI)  for ra2 but it need more options to support different mod for OpenRA ^^

**Comment by Phrohdoh** [comment]
@MichelKansou Awesome!
I will find some time soon to get it running on my system so I can produce screenshots. :-)

**Comment by MichelKansou** [comment]
@Phrohdoh it still need some work (currently I don't have too much free time) for now I use Bash for scripts so if anyone want to upgrade my wizard your welcome :) and if you find any issue make sure to create one [here](https://github.com/MichelKansou/OpenRA-MI/issues)

**Comment by ibrokemypie** [comment]
Think an official one shouldnt be developed until the mod is further completed, dont want it to be too easy for people who have no idea the state ra2 is in installing then complaining about it when it is unofficial and unfinished, keeping the involved install dissuades people who arent ready to face bugs and issues.

**Comment by MichelKansou** [comment]
@ibrokemypie of course I agree, I have just made an app that can be easily implemented in the future for all OpenRA projects and mods.

**Comment by abcdefg30** [comment]
#386 should cover this.
