### ISSUE TITLE
The name "cake" is not recognized as the name of a cmdlet, function, script file or executable program.

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#300]
![image](https://cloud.githubusercontent.com/assets/11130958/18615943/a3889298-7dd4-11e6-994c-eda5c698d237.png)

**Comment by abcdefg30** [comment]
You need to install cake first ([`0.13.0` release](https://github.com/cake-build/cake/releases/download/v0.13.0/Cake-bin-v0.13.0.zip)).

**Comment by yaaaaa** [comment]
thanks! its work
