### ISSUE TITLE
make: [fixheader.exe] Error: 127 on Ubuntu 16.04

### ISSUE THREAD

**Issue by SteamsDev** [OpenRA/ra2#301]
I keep getting this error when trying to make OpenRA on Ubuntu 16.04: `make: *** [fixheader.exe] error: 127`. Is this a "no fixheader.exe in ~/build/OpenRA" problem or is it something else?

**Comment by Phrohdoh** [comment]
`fixheader` is built from `packaging/fixheader.cs`:

```
mcs packaging/fixheader.cs -nologo -warn:4 -codepage:utf8 -unsafe -warnaserror -debug:full -optimize- -out:fixheader.exe -t:exe
-r:System.dll
-r:System.Core.dll
-r:System.Data.dll
-r:System.Data.DataSetExtensions.dll
-r:System.Drawing.dll
-r:System.Xml.dll
-r:thirdparty/download/ICSharpCode.SharpZipLib.dll
-r:thirdparty/download/FuzzyLogicLibrary.dll
-r:thirdparty/download/MaxMind.Db.dll
-r:thirdparty/download/MaxMind.GeoIP2.dll
-r:thirdparty/download/Eluant.dll
-r:thirdparty/download/SmarIrc4net.dll
```

Errorcode 127 just tells us that building a target failed, not why.
We'll have to see the full error to be able to tell you more.

In any case try this: `git clean -dfx && make dependencies && make`

**Comment by SteamsDev** [comment]
Sorry, here's what I get after `make dependencies && make`
`CSC fixheader.exe
make: mcs: command not found
Makefile:294: recipe for target "fixheader.exe" failed
make: *** [fixheader.exe] Error 127`

Like I said, I feel like it's because I don't have `fixheader.exe` in my OpenRA folder.

**Comment by chrisforbes** [comment]
This is mcs, the c# compiler, not being found. It's trying to build
fixheader, which is the first binary it needs to build. What happens if you
just do 'mcs' in a terminal? It may suggest a package.

**Comment by SteamsDev** [comment]
Cool. but now I have this error message:
`error CS0006: Metadata file "System.Data.DataSetExpansions.dll" could not be found.`
I looked in both the RA2 and OpenRA respiratory, and didn't see the specified file. Can you help?

**Comment by abcdefg30** [comment]
Is this still an issue on the latest version?

**Comment by 4thguy** [comment]
I managed to compile it just now, so if there was an error, it's not there any more

**Comment by abcdefg30** [comment]
Ok, good to hear. :)

**Comment by yoyojacky** [comment]
I am trying compile it on my Raspberry Pi 4B with Raspbian OS, 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
but encount this :
pi@rpi8g:~/OpenRA $ make dependencies
/bin/sh: 1: msbuild: not found
make: *** [Makefile:174: cli-dependencies] Error 127 
-----------
I have already installed mono-runtime package.
what should i do next?

**Comment by Mailaender** [comment]
Install `msbuild` from https://www.mono-project.com/download/stable/#download-lin-raspbian
