### ISSUE TITLE
unit "resources" do not see any new seqences names?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#311]
I add new resourse in wirld.yaml
```
ResourceType@Mud:
		ResourceType: 3
		Palette: resource
		Sequences: mud01
		MaxDensity: 20
		ValuePerUnit: 50
		Type: Mud
		Name: Mud
		PipColor: Yellow
		AllowedTerrainTypes: Clear, Rough
		AllowUnderActors: true
		TerrainType: Mud
```
and in tilesets yamls
```
TerrainType@Mud:
		Type: Mud
		AcceptsSmudgeType: SmallCrater, MediumCrater, LargeCrater, SmallScorch, MediumScorch, LargeScorch
		Color: 8470FF
		TargetTypes: Ground

```
after that, if I add new sequence name "mud01" to unit "resources", I have a crash:

> Exception of type `System.InvalidOperationException`: Unit `resources` does not have a sequence named `mud01`
[WinRAR archive.zip](https://github.com/OpenRA/ra2/files/566523/WinRAR.archive.zip)

**Comment by GraionDilach** [comment]
sequences/misc.yaml->resources entry lacks a mud01 sequence.

**Comment by yaaaaa** [comment]
but

`resources:
	Defaults:
		UseTilesetExtension: true
		Length: 12
		ShadowStart: 12
		Offset: 0, -15
	tib01: tib01
	mud01: mud01
		Length: 5
		ShadowStart: 0
	tib02: tib02
	tib03: tib03
	tib04: tib04
	tib05: tib05
	tib06: tib06
	tib07: tib07
	tib08: tib08
	tib09: tib09
	tib10: tib10
	tib11: tib11
	tib12: tib12
	tib13: tib13
	tib14: tib14
	tib15: tib15
	tib16: tib16
	tib17: tib17
	tib18: tib18
	tib19: tib19
	tib20: tib20
	gem01: gem01
		Length: 5
		ShadowStart: 0
	gem02: gem02
		Length: 5
		ShadowStart: 0
	gem03: gem03
		Length: 5
		ShadowStart: 0
	gem04: gem04
		Length: 5
		ShadowStart: 0
	gem05: gem05
		Length: 5
		ShadowStart: 0
	gem06: gem06
		Length: 5
		ShadowStart: 0
	gem07: gem07
		Length: 5
		ShadowStart: 0
	gem08: gem08
		Length: 5
		ShadowStart: 0
	gem09: gem09
		Length: 5
		ShadowStart: 0
	gem10: gem10
		Length: 5
		ShadowStart: 0
	gem11: gem11
		Length: 5
		ShadowStart: 0
	gem12: gem12
		Length: 5
		ShadowStart: 0`

**Comment by GraionDilach** [comment]
Then it's mud01.shp which is missing.

In any case, this isn't a modding support page.
