### ISSUE TITLE
Grand Cannon do not hurt dolphins

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#312]

**Comment by abcdefg30** [comment]
They actually do damage, but only if the dolphin is surfaced.

**Comment by Phrohdoh** [comment]
Is that the behaviour in vanilla RA2?

**Comment by MustaphaTR** [comment]
No, force firing reveals and damages submeged units in RA2 and Actually in RA too but i think it is changed in ORA for balance reasons.

**Comment by Mailaender** [comment]
It looks like the behavior changed. You can now force fire on dolphins/squids, they will resurface. Once they surface again, the turret stops shooting automatically.
