### ISSUE TITLE
Basic infantry keep crawling while/after shooting them with a tank

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#318]
As the title says, the basic infantry units (engineers + G.I's & conscripts) keep crawling while shooting them with a tank, even if they do not move on the field. The following GIF animation illustrates the issue:

![openra2-infbug_optimized](https://cloud.githubusercontent.com/assets/3705231/20038059/549f46d6-a435-11e6-81ec-0b689ca4b924.gif)

And as said, the same happens with Soviet infantry, too.

**Comment by Mailaender** [comment]
This doesn't happen anymore. Probably errors in the sprite sequence setups.
