### ISSUE TITLE
War Factories can't be build with "instant build speed" option enabled

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#319]
As the title says, War Factories cannot be built with "instant build speed" option enabled in debug menu. The countdown marker stays always at 00:01 and never says "Ready". Thus placing the building is impossible.

Both Soviet + Allies factions are affected.

**Comment by MustaphaTR** [comment]
Are you sure it is not just that you have not enough credits?

**Comment by Fincer** [comment]
Right, good point. Re-tested. This issue is invalid. Closing it. It was all about the credits I had. No problems when over 2000.
