### ISSUE TITLE
BuildingLimits not work

### ISSUE THREAD

**Issue by annopnod** [OpenRA/ra2#321]
limit 1 Barracks but ai create 2 Barracks

HackyAI@DogAI:
		Name: Dog AI
		BuildingCommonNames:
			ConstructionYard: gacnst, nacnst
			Refinery: garefn, narefn
			Power: gapowr, napowr, nanrct
			Barracks: gapile, nahand
			Production: gapile, nahand
		UnitsCommonNames:
			Mcv: amcv, smcv
		BuildingFractions:
			garefn: 1
			narefn: 1
			gapowr: 3
			napowr: 3
			gapile: 1
			nahand: 1
		BuildingLimits:
			garefn: 1
			narefn: 1
			gapowr: 3
			napowr: 3
			gapile: 1
			nahand: 1
		UnitsToBuild:
			dog: 100%
		SquadSize: 12

**Comment by MustaphaTR** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/11917

**Comment by abcdefg30** [comment]
Closing as upstream issue. Thanks for taking the time for a report, though.
