### ISSUE TITLE
Infantry hasn't attack animations

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#322]
As seen...

Allies:
![openra-ra2bug-infbug_1_optimized](https://cloud.githubusercontent.com/assets/3705231/20054063/e99f5f74-a4e3-11e6-878f-437d7eb16dcf.gif)

Soviet:
![openra-ra2bug-infbug_2_optimized](https://cloud.githubusercontent.com/assets/3705231/20054077/f58885c2-a4e3-11e6-8f1f-5abb6907ab79.gif)

(Sorry for bad GIF quality)

**Comment by Phrohdoh** [comment]
@abcdefg30 Any ideas about what may have broken this?

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/pull/11974

**Comment by abcdefg30** [comment]
Applied your patch from [`Fincer/openra-tibsunra2`](https://github.com/Fincer/openra-tibsunra2/blob/master/data/hotfixes/linux/hotfix-infantryanimations_shoot.patch): https://github.com/OpenRA/ra2/commit/0cadddeffdee50790f1f20a65a8ebc96b94039c3
