### ISSUE TITLE
Rocketeers near shadow (opaque black) appears in the air

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#323]
As seen in the following pic:
![openra-ra2bug-blackshadow-rocketeers](https://cloud.githubusercontent.com/assets/3705231/20054145/41eb4198-a4e4-11e6-9fac-8a9f11ca71a1.png)

**Comment by Fincer** [comment]
This happens only when rocketeers are in idle state. When they're flying, no additional shadows are present.

**Comment by MustaphaTR** [comment]
It is because they are using Landed graphics. When flying i think it plays same anim with moving in loop in original game.

**Comment by Fincer** [comment]
Found this pic showing the actual shadow behavior of rocketeers in original RA2:
![rocketeer](https://cloud.githubusercontent.com/assets/3705231/20242388/d1311f7c-a934-11e6-955a-370da543bc11.jpg)

Original image from C&C fan wiki (article: Rocketeer).

According to the picture, transparent ground shadow also differs.

**Comment by GraionDilach** [comment]
Yes, jumpjet infantry used the jjshadow.shp for shadow. This however is impossible to be reused atm:

 - There is no WithShadowOverlay trait - something which reciprocates WithShadow's render-at-ground behaviour for a selected overlay.
 - Even if there would be, jjshadow.shp is an SHP which starts with an empty frame and all SHPs with start with an empty frame crashes the OpenRA TS SHP reader.

**Comment by abcdefg30** [comment]
Fixed in https://github.com/OpenRA/ra2/commit/1a6b511650d283a35cfd4b83f5de6a30ababf894.
