### ISSUE TITLE
ai.yaml   BuildingFractions  

### ISSUE THREAD

**Issue by annopnod** [OpenRA/ra2#326]
ai.yaml can i use BuildingFractions as interger(1,2,3,4,5)  not percent(1%,2%,3%)

**Comment by Phrohdoh** [comment]
No, fractions are not absolute amounts.

**Comment by abcdefg30** [comment]
`BuildingFractions` is a `Dictionary<string, float>`. So in theory you could use integers, but they would I have no idea how the AI will handle a value > 100%.
If you don't want to use "%", you can just write the decimal (float) instead afaik. So e.g. 0.01 instead of 1%.
