### ISSUE TITLE
Holding down the mouse button doesn't drag the view

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#327]
At least the feature was present in the original RA2 title. Not sure, if it was present in TS, too.

Basically, the player viewpoint is not moving while dragging the cursor on the screen. This is expected behavior and improves the gameplay experience.

**Comment by GraionDilach** [comment]
Enable joystick scrolling in the controls.

**Comment by Fincer** [comment]
Okay. Didn't notice that before. Sorry for opening the issue. Closing it.

Fix: Go to settings -> Input -> Middle-mouse/Right-mouse scrolling -> Joystick
