### ISSUE TITLE
Demolition truck - Missing nuke explosion effect

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#337]
Title says it all

**Comment by MustaphaTR** [comment]
Demo trucks never had nuke explosion. They have small green explosion.

**Comment by Fincer** [comment]
Anyway, the main point is that they don't have *any* and I mean *any* explosion effect at all.

**Comment by MustaphaTR** [comment]
Demo truck has the  animation it should have. This can be closed i guess.

![resim](https://user-images.githubusercontent.com/7933210/35196790-0c87181a-fee8-11e7-871d-3f3ee7f17c6c.png)
