### ISSUE TITLE
stable ra2 compile but crashes (metrics.yaml)

### ISSUE THREAD

**Issue by v1nce** [OpenRA/ra2#342]
ra2 compile but crashed when runned into the openra stable current release.

I give up trying to run ra2.
After hours trying to run this thing I finally find that mod.yaml references 
	common|metrics.yaml
	ra2|metrics.yaml
but none of them references the following keys (that can be found in ra/metrics.yaml) which are needed  
	ButtonDepth: 1
	ButtonFont: Regular
	ButtonTextColor: FFFFFF
	ButtonTextColorDisabled: 808080
	ButtonTextContrast: false
	ButtonTextShadow: false
	ButtonTextContrastColorDark: 000000
	ButtonTextContrastColorLight: 7F7F7F
	ButtonBaseLine: 0
	CheckboxPressedState: false
	HotkeyFont: Regular
	HotkeyColor: FFFFFF
	HotkeyColorDisabled: 808080
	TextfieldFont: Regular
	TextfieldColor: FFFFFF
	TextfieldColorDisabled: 808080
	TextfieldColorInvalid: FFC0C0
	TextFont: Regular
	TextColor: FFFFFF
	TextContrast: false
	TextShadow: false
	TextContrastColorDark: 000000
	TextContrastColorLight: 7F7F7F

Now I got another error in Exts.cs in GetOrAdd.
Too much for me. I give up.

**Comment by abcdefg30** [comment]
> stable current release

Sorry, the RA2 mod can't be run with the stable release. You need the development version of OpenRA.

**Comment by v1nce** [comment]
OK but current stable ra2 doesn't work either with current bleed openra (https://github.com/OpenRA/ra2/issues/341) so this leave us ith no working version right now.
