### ISSUE TITLE
Can't locate type 'UpgradeManagerInfo'

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#346]
`Exception of type `System.InvalidOperationException`: Cannot locate type: UpgradeManagerInfo`

**Comment by MustaphaTR** [comment]
Upgrades are removed and replaced by conditions on upstream. RA2 mod has not upgraded for it yet.

**Comment by cookgreen** [comment]
but how to fix it? where to find the 'upgrademanagerinfo'? i try to search it in RA2 source code but failed

**Comment by MustaphaTR** [comment]
It is bot anything to do with C# code. It is about .yaml. UpgradeManagerInfo is replaced as i said.

**Comment by cookgreen** [comment]
And i debug the OpenRA source code, and still can't find.
I have found the problem is caused in Ruleset Function(OpenRA), the property 'DefaultRules' of ModData instance - moddata cased this error.

**Comment by MustaphaTR** [comment]
You can't find it because it no longer exists.

**Comment by cookgreen** [comment]
did you mean mod.yaml? i searched, but no results

**Comment by MustaphaTR** [comment]
No, .yaml files under rules folder and UpgradeManagerInfo is not really what you need to search, give me a sec to find the PR about it.

**Comment by cookgreen** [comment]
But which gives the openra this wrong parameter? something like yaml?

**Comment by MustaphaTR** [comment]
Tags that are removed/replaced.

**Comment by cookgreen** [comment]
okay, so how did we fix it?

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA/pull/12497/files

The tag `UpgradeManager:` is renamed to `ConditionManager:` that is the reason of error.

**Comment by cookgreen** [comment]
I have fixed this error and create a pull request

**Comment by GraionDilach** [comment]
Reverse duplicate of #354.
