### ISSUE TITLE
RA2 Crashed —— Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32` 

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#348]
`Exception of type `OpenRA.YamlException`: Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32` `

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/ra2/issues/341.
