### ISSUE TITLE
RA2 is outdated against bleed OpenRA.

### ISSUE THREAD

**Issue by Jehoel** [OpenRA/ra2#354]
I've been struggling for a few hours today to find a good commit in the openra repo (in both the `master` and `bleed` branches) which fully works with the ra2 mod, but there's always some problems.

I've had the most success with some commits around September 2016 where the solution with ra2 will build and run, and the ra2 mod begins to start, indeed it plays the RA2 background music, but there's a bunch of exceptions that happen during type-loading and processing the rules yaml where it fails. I don't want to log bugs because these issues are from targeting much older commits anyway.

The current state of the ra2 project is incompatible with the latest `bleed` commits because the yaml rules have changed considerably and so it needs upgrading, but I'm not familiar with the process, and doubtless the maintainers of this mod are aware of that.

Can the maintainers, or anyone else in the know, advise us which of the most recent openra commits are known to work and run ra2 successfully?

**Comment by samrocketman** [comment]
Use `git bisect` by marking a known good version (said there is one around March 2016 so use that) and marking a known bad commit (latest?).

It will help narrow it down quickly.  For reference, `git bisect` could find the broken commit in 180k commits within only 17 tries.  It's a log base 2 reduction.

**Comment by GraionDilach** [comment]
I'd start from https://github.com/OpenRA/OpenRA/tree/da591a90303b59a6c25cb2462f3e2f1ee5482253 against https://github.com/OpenRA/ra2/commit/fa23517643d1aa8c2d69a06c7772813640091bf6, since the last two ra2 commits were an engine fix but doesn't affect yamls.

**Comment by GraionDilach** [comment]
Oh wait, this was "I want to play" and not "I want to fix it up". Then yes, grab those two versions and that will work.

**Comment by Jehoel** [comment]
> Oh wait, this was "I want to play" and not "I want to fix it up". Then yes, grab those two versions and that will work.

It's both - really. But I can't fix it up until I'm at a known good point that at least runs :)

**Comment by GraionDilach** [comment]
Then start from there and only apply the soundtype commit when you reach the shellmap-revamp PR in OpenRA/OpenRA history,

**Comment by GraionDilach** [comment]
Closed all mod-is-outdated-crashes tickets in favor of this one since this one has the info required where to start/which versions to check out to get RA2 run.

**Comment by EngineGuy** [comment]
I started upgrading rules to new version of the game. But then I discovered that War Miner has different experience settings. Is this intentional?
```
	GainsExperience:
		Upgrades:
			200: firepower, damage, speed, reload, inaccuracy, rank
			400: firepower, damage, speed, reload, inaccuracy, rank
			800: firepower, damage, speed, reload, inaccuracy, rank
			1600: firepower, damage, speed, reload, inaccuracy, rank, eliteweapon, selfheal

```

**Comment by pchote** [comment]
Once https://github.com/OpenRA/OpenRA/pull/12638 has been merged I suggest migrating this mod over to a structure like [pchote/OpenRAModTemplate](https://github.com/pchote/OpenRAModTemplate) to fix these issues for good.

**Comment by m3ntalsp00n** [comment]
@EngineGuy - no idea. Thought it was dead code. Guys talking about it tho, the war miner was supposed to be a weapon at higher levels.

If you're interested I have a working version in my repo that works against bleed, trying to merge into PR #347.
