### ISSUE TITLE
RA2 Crashed - can't find field

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#357]
Exception of type `System.MissingFieldException`: can't find field:“OpenRA.World.ActorMap”。
   in OpenRA.Mods.RA2.Traits.WithExitOverlay.get_IsExitBlocked()
   in OpenRA.Mods.RA2.Traits.WithExitOverlay.<.ctor>b__2()
   in OpenRA.Mods.Common.Traits.Render.RenderSprites.AnimationWrapper.get_IsVisible()
   in OpenRA.Mods.Common.Traits.Render.RenderSprites.<Render>d__5.MoveNext()

**Comment by abcdefg30** [comment]
I couldn't reproduce this on my end. What did you do to get this crash? (Are you maybe using an outdated version of OpenRA?)

**Comment by cookgreen** [comment]
No, OpenRA what i use is up-to-date

**Comment by cookgreen** [comment]
Fixed and closed
