### ISSUE TITLE
Idea: New Trait - Airship

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#358]
The problem in ra2 mod is the Kirov Airship, In ra2, Westwood makes a new kind of aircraft, it is the Kirov Airship, the Kirov will throw the bombs to enemy units directly not like the Aircraft in OpenRA, it is not like the AttackBomber either.
In ra2 mod, we use Aircraft to describe the Kirov, but it is not enough, so we need a new trait to describe the Kirov
Yes, there is no Airship in original OpenRA, but i think we need to give support to the people who want to create something like Kirov

Of course, we can give more options to make people implemt their own style Airship, not only Kirov, it can be Zeppelin

**Comment by cookgreen** [comment]
#226

**Comment by GraionDilach** [comment]
This is possible already, as once explained.
