### ISSUE TITLE
UI Missing bottom bar

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/ra2#364]
![](https://i.ytimg.com/vi/_sO2ckaPpVs/hqdefault.jpg)

The bottom bar as seen above is missing. This is used to select command/attack modes + formations

**Comment by Jehoel** [comment]
OpenRA (and I assume the RA2 mod) strives for a more minimalist UI - the bottom-bar just serves as a mouse-driven way to access a limited subset of keyboard shortcuts.

I do agree the button-bar was useful for beginner players, people who can only use a mouse, and it's a useful shortcut.

I think a better idea would be for OpenRA upstream to make it easier for mods to have a "command shortcut" UI pane.

**Comment by abc013** [comment]
As we are now able to implement a command bar, one question is how the command bar should look like.
@x-a-n-a-x already made one, but there are still the click-textures missing:
![image](https://user-images.githubusercontent.com/21260178/29129469-31055e56-7d27-11e7-9282-a2bce432398a.png)

I thought we could recreate the old one like that:
![controlbar](https://user-images.githubusercontent.com/21260178/29129407-f79becd4-7d26-11e7-817d-2c5d8ca71b5b.png)
and use the old command pics.

**Comment by x-a-n-a-x** [comment]
That would make more sense indeed. 
Other opinions ?

**Comment by GraionDilach** [comment]
Only deploy has an 1:1 equvivalent between RA2 and OpenRA. Sure, there are also waypoints (which AFAIK differ a bit) and Guard has the defense shield icon but the rest would still need new glyphs.

**Comment by MustaphaTR** [comment]
There is also stop in original which can be used for well stop, but i think it may fit Hold Fire better.

**Comment by Mailaender** [comment]
We are moving towards an engine version where we can add this. Depends on https://github.com/OpenRA/ra2/pull/393#issuecomment-351023586.

**Comment by Jehoel** [comment]
@GraionDilach I'm thinking about how/if they would support Tiberian Sun-style waypoints, or keep the current RA2-style temporary waypoints? It would be nice if we could have both because they're good for setting-up patrol cycles and for coordinating simultaneous attacks, but deleting them afterwards is a pain.

**Comment by xan2622** [comment]
Here it is: https://github.com/xan2622/OpenRA/tree/RA2_commandbar

![capture_01_allies](https://user-images.githubusercontent.com/1732773/36277798-3621d148-1292-11e8-8c4a-277ceb0ffb86.PNG)

![capture_01_soviets](https://user-images.githubusercontent.com/1732773/36277800-3ac17c1c-1292-11e8-8bad-24b895ea7be7.PNG)
