### ISSUE TITLE
Money lost when Ore Refinery was destroyed

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#372]
When Ore Refinery was destroyed, the Player own Money will lost some

**Comment by MustaphaTR** [comment]
That's normal, not a bug. You lose the money if you don't have another space to store it like silos or other refs.

**Comment by GraionDilach** [comment]
Technically, it still is a bug - RA2 isn't supposed to use storage logic, however OpenRA is hardcoded to rely on it. Best workaround I could came up with in AS was to have a trait to provide capacity on the player actor.

**Comment by MustaphaTR** [comment]
Oh, my bad. I thought there was OpenRA/OpenRA. My bad.

**Comment by cookgreen** [comment]
@MustaphaTR Ore Refinery was destroyed and there is no money lost in original RA2

@GraionDilach So how did we solve this problem?

**Comment by abc013** [comment]
You could spawn the storaged ore as the refinery explodes, like harvesters do in RA.

**Comment by abcdefg30** [comment]
(Ah now I see what you asked me about yesterday. ^^) Actually, refineries in RA2 shouldn't store resources at all, so fixing that should also fix this here. (See Graion's comment.)

**Comment by GraionDilach** [comment]
https://github.com/AttacqueSuperior/Engine/commit/8cf23c4605e4532bfd7f2856ea366cadc5336658 should prolly be shifted to upstream but I lost interest in doing so.

**Comment by MustaphaTR** [comment]
This should be fixed by https://github.com/OpenRA/ra2/commit/ef88090e57d9a0c155beac5970db64f0d8528d84
