### ISSUE TITLE
Error CS0006 on Ubuntu 16.04

### ISSUE THREAD

**Issue by SteamsDev** [OpenRA/ra2#373]
I have received a new error message on Ubuntu 16.04 build terminal:
`Error: CS0006: Metadata file "System.Data.DataSetExtensions.dll" could not be found.`
I don't exactly know what the file specified is and I didn't see it in the OpenRA or RA2 file system. Any ideas?

**Comment by abcdefg30** [comment]
Do you have the latest version of Mono installed?

**Comment by SteamsDev** [comment]
I'm not sure. How do I check?

**Comment by abcdefg30** [comment]
`mono --version` should do it.

**Comment by SteamsDev** [comment]
Mono version is 4.2.1 with architecture amd64.

**Comment by abcdefg30** [comment]
Sorry, as I'm not using linux I don't have any idea. :/
While searching I came across http://packages.ubuntu.com/precise/all/libmono-system-data-datasetextensions4.0-cil/filelist which means you should actually have that dll (as you got Mono >= 4.0). The also have it on their git repository https://github.com/mono/mono/tree/master/mcs/class/System.Data.DataSetExtensions.

Maybe reinstalling Mono helps (if the dll is really missing).
Does normal OpenRA run fine for you or is this only a problem with RA2?

**Comment by Fincer** [comment]
On my Arch Linux system, I have that file in multiple paths:

- /usr/lib/mono/2.0-api/System.Data.DataSetExtensions.dll 
- /usr/lib/mono/4.0-api/System.Data.DataSetExtensions.dll 
- /usr/lib/mono/4.5-api/System.Data.DataSetExtensions.dll

By doing little research, I can verify these files are part of 'mono' package (obviously):

```
[fincer@fincer-laptop /]$ pacman -Qo /usr/lib/mono/2.0-api/System.Data.DataSetExtensions.dll 
/usr/lib/mono/2.0-api/System.Data.DataSetExtensions.dll is owned by mono 4.8.0.495-1
```

According to Ubuntu Packages site, the following Ubuntu specific packages have the missing file:

libmono-system-data-datasetextensions4.0-cil
mono-reference-assemblies-4.0

You may try installing both or one of those packages by running:

`sudo apt-get update && sudo apt-get install libmono-system-data-datasetextensions4.0-cil mono-reference-assemblies-4.0`

and then re-run OpenRA.

**Comment by SteamsDev** [comment]
It worked! Thank you.
