### ISSUE TITLE
Delete ActorGroupProxy (rules/player.yaml)

### ISSUE THREAD

**Issue by Fincer** [OpenRA/ra2#374]
ActorGroupProxy stil exists in player.yaml, preventing the RA2 mod to start

Reference:
https://github.com/OpenRA/OpenRA/commit/880f90345e28f895588aa357dad84e4c1f0d7a4e

**Comment by abcdefg30** [comment]
Thanks for the reminder. Removed it inhttps://github.com/OpenRA/ra2/commit/a6a1fd5eae2fa2e80ac577f495ae04c20ed2755a.
