### ISSUE TITLE
Actor Actor1110 of unknown type bridge2

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#378]
I try to import a mission map from original ra2, when i finish and go into the game, it noticed "Actor Actor1110 of unknown type bridge2" and exited

**Comment by Fincer** [comment]
Possibly same issue (or similar) than https://github.com/OpenRA/ra2/issues/329

**Comment by Mailaender** [comment]
Actually that is an elevated bridge. #329 is about ground bridges.

**Comment by Mailaender** [comment]
Fixed by https://github.com/OpenRA/ra2/pull/685.
