### ISSUE TITLE
OpenRA crashed when loading the ra2 mod during manifest parsing

### ISSUE THREAD

**Issue by jack77er** [OpenRA/ra2#389]
Hi everyone, i've hot some trouble after building the ra2 mod from the github sources.

Error Messages her: https://pastebin.com/20GviQRB

Any advise?

**Comment by jrb0001** [comment]
This error message looks like you are using a version of the engine which is newer than what the mod supports.

**Comment by jack77er** [comment]
Yeah possible, I've build it from the sources from Github yesterday by using the step by step walkthrough https://github.com/OpenRA/ra2/wiki/Step-by-Step . Would it be possible to fix that? To adapt the mod to the new engine version?

**Comment by abcdefg30** [comment]
You can try using #386. The Step-by-Step guide probably doesn't work by now anymore, indeed.

**Comment by abcdefg30** [comment]
#386 is merged, so it should work again.
