### ISSUE TITLE
Crash After Win

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#39]
Red Alert 2 Mod at Version {DEV_VERSION}
on map 8686e762dbe6b6a2a032e5b19bb1dcc686d7f18e (dustbowl by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: The current order generator may not be changed from synced code
   в OpenRA.Sync.AssertUnsynced(String message) в d:\Games\OpenRA-bleed\OpenRA.Game\Sync.cs:строка 200
   в OpenRA.World.set_OrderGenerator(IOrderGenerator value) в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 131
   в OpenRA.World.CancelInputMode() в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 138
   в OpenRA.Mods.Common.Widgets.Logic.MenuButtonsChromeLogic.OpenMenuPanel(MenuButtonWidget button, WidgetArgs widgetArgs)
   в OpenRA.Mods.Common.Widgets.Logic.MenuButtonsChromeLogic.<>c__DisplayClass1c.<.ctor>b__3()
   в OpenRA.Mods.Common.Widgets.Logic.LoadIngamePlayerOrObserverUILogic.<>c__DisplayClass6.<.ctor>b__2()
   в System.Action.Invoke()
   в OpenRA.World.EndGame() в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 64
   в OpenRA.Mods.Common.Traits.MissionObjectives.<>c__DisplayClassf.<CheckIfGameIsOver>b__c()
   в OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime) в d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:строка 52
   в OpenRA.Game.LogicTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 574
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 709
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 749
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 117
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 39

**Comment by Phrohdoh** [comment]
This is an OpenRA proper bug.
https://github.com/OpenRA/OpenRA/pull/10523

**Comment by abcdefg30** [comment]
The fix for this was just merged into upstream OpenRA.
