### ISSUE TITLE
the combat AI doesn't auto attack

### ISSUE THREAD

**Issue by piperun** [OpenRA/ra2#398]
While the enemy/friend AI does direct their forces to attack at certain targets and you as the player can do so too, but the units themselves don't open automatically fire upon most enemy units or buildings (enemy or neutral).

**Comment by GraionDilach** [comment]
Probably AutoTargetingPriorities are messed up.

**Comment by joker5bb** [comment]
i also have this problem

**Comment by Mailaender** [comment]
I checked and believe this isn't a problem anymore.
