### ISSUE TITLE
Lag spike after each song played

### ISSUE THREAD

**Issue by piperun** [OpenRA/ra2#399]
If you play on any map after a song has ended and a new one is loaded in, it freezes the game for about 0.5sec (it shows a spike on the white-grey line on the performance graph).

**Comment by pchote** [comment]
This has been fixed upstream, but the ra2 mod is currently using an older engine version that doesn't include the fix.

**Comment by Mailaender** [comment]
Resolved by 5d89d8cf06405b97c1ff763fd7e11886deca3db7 I assume.
