### ISSUE TITLE
Migrate to the OpenRA Mod SDK?

### ISSUE THREAD

**Issue by Blakeley00** [OpenRA/ra2#401]
As I'm sure you guys already know modifying the base OpenRA code directly is no longer supported and they now provide a [modding SDK](https://github.com/OpenRA/OpenRAModSDK) that makes it much easier for your players/testers to compile and run custom mods.

Looking forward to you guys releasing a new easy to install version of your mod for this new OpenRA!

Then I can show it to the all folks asking "how how how??" on my OpenRA RA2 videos lol. They're getting quite a lot of hits so there's definitely plenty of people wanting to try your mod but are just too intimidated by the complex installation (for the average Joe) that the old version required.

2 Player game that sadly crashed
[https://www.youtube.com/watch?v=Ih7pvQFuM9Q](https://www.youtube.com/watch?v=Ih7pvQFuM9Q)

1 Player game that seems to have become very popular
[https://www.youtube.com/watch?v=NGt6klPU3Gk](https://www.youtube.com/watch?v=NGt6klPU3Gk)

**Comment by GraionDilach** [comment]
>As I'm sure you guys already know modifying the base OpenRA code directly is no longer supported 

Wrong. Infact, the opposite, the mod SDK and the changes related to it (aka mods should ship it's own engine version) allowed the infrastructure to explicitly support soft-forks. The sole issue with the old RA2 installation method is that Average Joes are incapable of understanding the fact they need explicit versions, even though it has been said numerous times including the readmes.

Anyway, this repo already shifted to the Mod SDK AFAIK (with #386 and nonPR followups), it's just probably on a pre-hitboxes engine version even.

**Comment by abcdefg30** [comment]
> Anyway, this repo already shifted to the Mod SDK AFAIK (with #386 and nonPR followups), it's just probably on a pre-hitboxes engine version even.

Yes, we already use the SDK, just don't have customized hitboxes yet (so damaging is a bit broken at the moment). Sorry for the late response, btw.
