### ISSUE TITLE
Desolitor shot have not original weapon rendering?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#43]
![default](https://cloud.githubusercontent.com/assets/11130958/12372204/13cffb58-bc7a-11e5-9585-6ec74c5021f4.png)

last time I used Desolitors in Phrohdoh's repo, and it'll be fine.

**Comment by GraionDilach** [comment]
Line (contrail, laser) widths have been readjusted since in upstream and the fallback default ended up being scaled with cellsize, which due to RA2 having huge tiles compared to say RA1 ended up wider as well.

Also, Desos never had their RA2 effect, because that one is a sinus wave and not a line.

**Comment by yaaaaa** [comment]
maybe I have something confused. probably baffled me that before this wave has a different color

**Comment by MustaphaTR** [comment]
That would be better if we change color of it to green as a start. Purple looks too unreleated.

**Comment by Phrohdoh** [comment]
Upstream does not have paletted line rendering yet so we cannot remap the line drawn, so there is no point changing it yet.

@abcdefg30 what is the bug here?

**Comment by GraionDilach** [comment]
The Desolator's beam wasn't remappable, but green - https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L752. Both the width and colors are bug.

**Comment by Phrohdoh** [comment]
[Generate a sine wave](http://math.stackexchange.com/questions/196207/drawing-sine-and-cosine-waves) and pass the world-space points to [WorldRenderer.ScreenPosition](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/WorldRenderer.cs#L206) then those `float2`s to [the RgbaColorRenderer](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/RgbaColorRenderer.cs).

**Comment by Phrohdoh** [comment]
[WIP](https://github.com/Phrohdoh/OpenRA/tree/sine-beam):
![deso-test-03](https://cloud.githubusercontent.com/assets/4861023/16424083/48a7ae72-3d24-11e6-8847-25dfbd0e7e77.gif)

**Comment by forcecore** [comment]
With my Railgun PR in bleed, I think I have a good chance of getting the sine beam into upstream, too. The code won't be too different.

**Comment by Nihilianth** [comment]
I've tried to implement this using the Railgun code. I had to modify it a bit in terms of offsets / using only the sine beam etc. I am unsure though whether I should submit a PR with it, since this mostly a copy paste of the Railgun / RailgunRenderable code.

But here's the result so far:
![2019-01-10 12_52_08-openra game 2019-01-10 12-49-42-784 mp4 - vlc media player](https://user-images.githubusercontent.com/6731717/50966880-ad9fd200-14d6-11e9-840f-17acdc9b2b29.png)

And a [vid:]( https://www.youtube.com/watch?v=5yQ6R4lv0Rg&feature=youtu.be)

**Comment by MustaphaTR** [comment]
We already have a working Sinus Beam rendering written by BoolBada in RV, tho looking at this Railgun projectile looks pretty cool too.

**Comment by GraionDilach** [comment]
For the record: the RV Radbeam is indeed forcecore with a few style updates/cleanup here'n'there.

https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Projectiles/RadBeam.cs
https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Graphics/RadBeamRenderable.cs

If you managed to clean up beyond, do. if you don't then mix the two, and do it thenafter. The RA2 repo ends up better with either.

**Comment by Nihilianth** [comment]
Oh I didn't think of checking any forks first. That one by forcecore seems to work pretty much the same, except that it also tracks the target. Though I wasn't able to make the beam go from the desolator's weapon to the target without cs code changes, atm its rendered at the unit's feet (Found out about openra just a couple of days ago, so maybe I am missing something in the rules file).

**Comment by MustaphaTR** [comment]
What you are looking for is Armament>LocalOffset.

**Comment by Nihilianth** [comment]
@MustaphaTR thanks, that's exactly what I've been looking for.
I'm not sure how to handle it from now on tho. Should I submit a PR with that, even though the code is basically from the AS repo?

**Comment by MustaphaTR** [comment]
Yes, go ahead and do a PR. There are other traits that are on AS which are already on RA2.dll too.

**Comment by pchote** [comment]
There is a $5 bounty on this that can (hopefully still?) be claimed before the timer expires at the end of the month.

**Comment by Mailaender** [comment]
Pinging @forcecore who was the original author of the code I submitted.

**Comment by forcecore** [comment]
Uhmm I'm not sure whether I should take the bounty, even if I did, I'd donate back to some other bounties anyway like the unit waypoint visualization bounty.

**Comment by Mailaender** [comment]
If you don't take the bounty, BountySource will collect it as unclaimed and it will be lost.

**Comment by forcecore** [comment]
I can't find the bounty, searching for deso, desolator, beam didn't yield any results.

**Comment by pchote** [comment]
https://www.bountysource.com/issues/29931106-desolitor-shot-have-not-original-weapon-rendering
