### ISSUE TITLE
DEFCON has gems instead of Ore

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ra2#437]
This is the DEFCON from original game. Importer i think messed up the extra 2 tib types/they are used differently in TS and RA2. May be the case in another map too.

![defcon](https://user-images.githubusercontent.com/7933210/35347955-b5bcb032-0147-11e8-80f5-7a2dddab9b98.png)

**Comment by GraionDilach** [comment]
DEFCON is affected by the classic RA2-mappers-used-third-ore-instead-of-first-ore issue. This isn't a bug of the importer.

**Comment by GraionDilach** [comment]
You coulda fix this longterm if you duplicate/edit https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Cnc/UtilityCommands/ImportTSMapCommand.cs#L218 with the tib2 list listed for resource 0x01 instead of 0x02.

**Comment by MustaphaTR** [comment]
Duplicating TS map importer as `--import-ra2-map` can be good. Current TS map importer doesn't import some stuff like fences either so we an add them too. I used an edited ImportTSMapCommand.cs to create fixed version of DEFCON 6 and Snow Valley anyway.

**Comment by GraionDilach** [comment]
No, the other two tibs were unused pretty much in base TS and were used as the red (for tib02) and purple (for tib03) tibs in modmaps.
