### ISSUE TITLE
Rocket Troop has shadow on the ground

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#448]
![openra-2018-01-28t024654176z](https://user-images.githubusercontent.com/21171007/35478515-6ad12c12-041a-11e8-99d3-7c1f882d88a2.png)

In original ra2, it just has a round point on the ground

**Comment by GraionDilach** [comment]
https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/Render/WithIdleOverlayOnGround.cs was written to fix this.

**Comment by cookgreen** [comment]
@GraionDilach when will you guys fix the voxel render in ra2? it is too terrible.

**Comment by cookgreen** [comment]
@GraionDilach when will you guys fix the voxel render in ra2? it is too terrible.

**Comment by cookgreen** [comment]
@GraionDilach when will you guys fix the voxel render in ra2? it is too terrible.

**Comment by cookgreen** [comment]
@GraionDilach when will you guys fix the voxel render in ra2? it is too terrible.

**Comment by cookgreen** [comment]
@GraionDilach when will you guys fix the voxel render in ra2? it is too terrible.

**Comment by GraionDilach** [comment]
- The voxel renderer is beyond my skillset.
 - At this point, I haven't seen any worthwhile solution to the voxel renderer anyway. The last proposition seriously suggested to dumb down voxels to WW level, which is craptastic and took the community a decade to work around the issues it causes.
 - Incase you haven't noticed, I am a _contributor_, not a developer and I am not interested being the latter for reasons including lack of time, lack of motivation and basically being burnt out for the time being.

**Comment by cookgreen** [comment]
@GraionDilach That's why I say "you guys" not "you".

**Comment by cookgreen** [comment]
@GraionDilach Don't misunderstand my meaning, I didn't order any of you guys to do anything. I just want to know when will you guys fix it if you guys have time, If you guys lack of time to fix, then leave it alone. I can understand that.
