### ISSUE TITLE
Can't Automatic Attack Troop

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#449]
![openra-2018-01-28t034130670z](https://user-images.githubusercontent.com/21171007/35478759-22be7fea-0421-11e8-8399-cfed4a30dce9.png)
As you guys can see, my troop didn't attack enemy's engineer unless I attack manually

There is another bug like this:
![openra-2018-01-28t034400962z](https://user-images.githubusercontent.com/21171007/35478764-4be8d6ea-0421-11e8-9aca-10fe0206541e.png)
My base was under attacked by enemy troops, but my base still there even suffer so much damage

**Comment by MustaphaTR** [comment]
No auto target should be fixed by https://github.com/OpenRA/ra2/pull/430

**Comment by cookgreen** [comment]
why can't my base be destroyed by enemy troops?

**Comment by MustaphaTR** [comment]
That should be fixed by #407. RA2 mod has been left really behind compared to engine. My PR should fix such cases except missing command bar, but i and @xan2622 are on in too.
