### ISSUE TITLE
Request for addition : skirmish save settings

### ISSUE THREAD

**Issue by MDPI314** [OpenRA/ra2#452]
Would it be possible to save all skirmish settings, either automatically or manually, I mean :
- AI Skill
- Colors
- Teams
- Map and starting positions

from one game to another, at least to change minimal things instead of having ALL to be reconfigured the next time I play :-/

PS: I'm using OpenRA release-20171014 currently , Red Alert 2 mod

**Comment by xan2622** [comment]
Related to https://github.com/OpenRA/OpenRA/issues/4122 I guess.

**Comment by MDPI314** [comment]
Maybe. Not obvious for me without the knowledge of how it's developped/written. These options are not on the same page as the other "checkboxes" options related there.

**Comment by Mailaender** [comment]
Either way this is a feature for the engine, not this mod.

**Comment by MDPI314** [comment]
Hi, thank you for "closing" the subject but ... did you transfer it to the appropriate location ?
I hope you understand normal people like me does not know how the entire project is built, and if this is some "engine" question, you indeed asked/linked my subject to the right place/persons in charge.

Best regards,
A simple user, player, and fan from the beginnings (original Westwood Red Alert game).

**Comment by chrisforbes** [comment]
I've created the matching issue for you on the engine side.

**Comment by MDPI314** [comment]
Thanks a lot ;-)
