### ISSUE TITLE
Missing: OpenRA.Traits.IMouseBoundsInfo 

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/ra2#457]
Exception of type `OpenRA.YamlException`: ActorInfo("gawall") failed to initialize because of the following:
Missing:
OpenRA.Traits.IMouseBoundsInfo

**Comment by Mailaender** [comment]
Can you give some more context? Did you try to update the mod engine on your own?

**Comment by cookgreen** [comment]
Well, the thing is that I imported a map from original ra2, and deleted the things that OpenRA can't recognize, I use map editor edit this map and want to play it with script I write for it, but it crashed and noticed me this.
What version I use is the newest {DEV_VERSION}

**Comment by cookgreen** [comment]
BTW, the `gawall` is Allied Wall in ra2, it seems missing some trait like 'Bounds', but I am not sure a wall truely need this trait.

**Comment by cookgreen** [comment]
@Mailaender And I complied the ra2 new version, when i want to try skirmish but it crashed and noticed same error `Exception of type `OpenRA.YamlException`: ActorInfo("tree28") failed to initialize because of the following:
Missing:OpenRA.Traits.IMouseBoundsInfo `

**Comment by Mailaender** [comment]
You should use the accompanying scripts to build and use the engine release this was made for - not the latest OpenRA version. https://github.com/OpenRA/ra2/wiki has instructions.

**Comment by cookgreen** [comment]
@Mailaender What will do if ra2 want to merge into newest OpenRA engine

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/wiki/Upgrading-mods-to-a-new-release though that page doesn't look up-to-date. It basically boils down to running the utility upgrade command and then do some more changes which aren't automated manually.
