### ISSUE TITLE
Harrier/Blackhawk can't land once it takes off

### ISSUE THREAD

**Issue by hathlife** [OpenRA/ra2#486]
So far the allies Harrier/Blackhawk can't land once it takes off .I know that this is because some missing code, so I want to know where should I start to fix.

**Comment by Mailaender** [comment]
This isn't an easy one. I assume it has something to do with the landing code in https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs not working properly on maps with heights.

**Comment by hathlife** [comment]
[See here](https://h0nm4m31k0.tk/?p=37&preview=true)
Issue seems to be basically solved with engine version playtest-20200118. However there're still something need to be polished and I find another critical issue. I will create them later.
