### ISSUE TITLE
Installation RA2 mod on MacOS 

### ISSUE THREAD

**Issue by knightjp** [OpenRA/ra2#491]
![screen shot 2018-10-13 at 1 19 49 pm](https://user-images.githubusercontent.com/14360736/46903785-0f0dd000-ceeb-11e8-8496-107180e2d08c.png)
I followed the instructions on the wiki.. but I'm not able to work. I assumed that if I installed OpenRA, I would get RA2 (my fav) with it. Since this isn't the case, how do I get it installed on my machine.

**Comment by knightjp** [comment]
> Looks like the content is not installed. You can try using the `Advanced Install` if you have the original RA2 disk or an Origin install.
> Otherwise https://github.com/OpenRA/ra2/wiki#installing-the-content-manually might help.

Thank you.. I figured that out.. It turns out that I needed ra2.mix as well as the other .mix; which aren't in the download from this github page. That's a bog question why they're not here. They should be. It would make things a lot more easier to understand as the wiki page mentions them, but doesn't tell us where to find them.

**Comment by MustaphaTR** [comment]
> That's a bog question why they're not here. They should be. It would make things a lot more easier to understand as the wiki page mentions them, but doesn't tell us where to find them.

That's because RA2 is not freeware. Technically you need to own the game to be able to play the OpenRA mod. Tho you can always pirate it.
