### ISSUE TITLE
`Beacon.New` in scripting uses `PlaceBeacon` but RA2 only has `PlaceSimpleBeacon`

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/ra2#501]
Should RA2 also support `PlaceBeacon` or should the upstream logic grow to support `PlaceSimpleBeacon`?

---

Attempting to use `Beacon.New` in scripting results in:

```
System.InvalidOperationException: TypeDictionary does not contain instance of type `OpenRA.Mods.Common.Traits.PlaceBeaconInfo`
```

Because, as stated, the `Player` definition only has `PlaceSimpleBeacon`:

https://github.com/OpenRA/ra2/blob/b9c872788ff3ca70539bd40ba10811365b187235/mods/ra2/rules/player.yaml#L60

**Comment by MustaphaTR** [comment]
We need the scripting to work with PlaceSimpleBeacon. Also seems like an upstream issue, since PlaceSimpleBeacon isn't a OpenRA.Mods.RA2 trait.

**Comment by Phrohdoh** [comment]
Deciding whether to change RA2 (add or swap traits) is specific to RA2 so that's why I opened *this particular* ticket here.

**Comment by MustaphaTR** [comment]
RA2 beacon consist of 1 image, not 2 that's why we use PlaceSimpleBeacon. There isn't anything to change here.

**Comment by Phrohdoh** [comment]
Ok, that answers the question in the OP. ;)
