### ISSUE TITLE
Navy Seal stays in firing frame a bit too long before idling

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/ra2#503]
I don't know if this is a logic issue or if the idle sequence is off by a frame.

After the Navy Seal kills a target they are rendered for a second or two with a static muzzle flash, but should already be idling.

**Comment by MustaphaTR** [comment]
Same happens when you give them stop command too. Afaik this is something that was happening on main mods too but recently fixed but isn't on the engine version RA2 mod using yet.

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/pull/15701 might have fixed this.

**Comment by ZxGanon** [comment]
There is also an issue where Tanya and Seals get stuck on their attacka nimation while swimming.
You just have to force fire and than stop command to let that visual bug appear.

**Comment by Mailaender** [comment]
Engine was updated.
