### ISSUE TITLE
Installation:  Lua 5.1 library detection failed

### ISSUE THREAD

**Issue by eX00r** [OpenRA/ra2#542]
Following the wiki instructions after 'make' downloaded several things I got this error and installation was aborted. I installed lua5.1. I am running Ubuntu 18.04.

make[1]: Verzeichnis „/home/***/***ra2-master/engine“ wird betreten
Lua 5.1 library detection failed.
Makefile:306: recipe for target 'linux-native-dependencies' failed
make[1]: *** [linux-native-dependencies] Error 1
make[1]: Verzeichnis „/home/***/***/ra2-master/engine“ wird verlassen
Makefile:74: recipe for target 'engine' failed
make: *** [engine] Error 2

I would be very thankful if you could provide some help getting this to run on my machine.

**Comment by matjaeck** [comment]
See OpenRA/OpenRA#16070 and OpenRA/OpenRA#16074.

**Comment by matjaeck** [comment]
OpenRA/OpenRA#16075 has a list of required packages for Ubuntu 18.04.

**Comment by eX00r** [comment]
Thanks!
