### ISSUE TITLE
Tech Structures are missing rubbles.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ra2#555]

**Comment by sorcerer86pt** [comment]
Can confirm this:

- Airport
- Hospital
- Oil Drill

Each of these doesn't have a rubble associated.

**Comment by GraionDilach** [comment]
Tech Outpost also have rubble associated _but only within the snow artwork_.

**Comment by indivisibleman** [comment]
As the Tech Outpost has no rubble art for Urban and Temperate tilesets should it only be placed in Snow maps?

**Comment by sorcerer86pt** [comment]
Hell yeah, nice one
