### ISSUE TITLE
i keep getting a fatal error!

### ISSUE THREAD

**Issue by Wick3d77** [OpenRA/ra2#571]
non of the 3 games work on my computer it just says fatal error and nothing else

**Comment by abcdefg30** [comment]
What is the content of the exception log? Without it we can't help you.

**Comment by Wick3d77** [comment]
It doesn't say what the error is all it gives me is a box that says view FAQ and quit

**Comment by abcdefg30** [comment]
You have to retrieve the log file from the logs folder, see https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed

**Comment by Wick3d77** [comment]
I have managed to get in the logs folder what file do I look for to find out why its a fatal error

**Comment by Wick3d77** [comment]
[exception-2019-07-06T122611Z.log](https://github.com/OpenRA/ra2/files/3364670/exception-2019-07-06T122611Z.log)

**Comment by abcdefg30** [comment]
Looks like the game can't access your Documents folder. (Is that folder in a cloud?)
You can try working around this by creating a folder named `Support` inside the game directory.

**Comment by Wick3d77** [comment]
ok thank you I moved the intire folder and now its working fine :)
