### ISSUE TITLE
Use Latest Released OpenRA Engine

### ISSUE THREAD

**Issue by dchokola** [OpenRA/ra2#572]
Lots of changes between releases and RA2 hasn't kept up-to-date.

I had an honest go at a patch, but it still needs work before the game will run.

[release-20190314.patch.txt](https://github.com/OpenRA/ra2/files/3365299/release-20190314.patch.txt)

**Comment by MustaphaTR** [comment]
I wasn't even aware we weren't using the lastest engine. Will do an update soon.
