### ISSUE TITLE
Crash on Defense Tab Selections

### ISSUE THREAD

**Issue by dchokola** [OpenRA/ra2#574]
When selecting items in the defense structures tab, there is a probability that the game will crash. There seems to be a higher probability of the game crashing while playing a multiplayer game (incl. single-player on a remote server) and selecting something on the defense structures tab. All crashes happen after clicking on a defense structure's icon after it has finished building (i.e. READY). The game locks up for about a minute, then eventually segfaults. I'm including a backtrace from gdb after a crashed skirmish where I went to place a grand cannon.

More info:
```dan@ender:~/projects/ra2$ ./launch-game.sh 
Platform is Linux
Engine version is release-20190314
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL version: 4.6.0 NVIDIA 418.74
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (release-20190314)
	ra2: Red Alert 2 (git-b9668d9)
	all: All mods (release-20190314)
	cnc: Tiberian Dawn (release-20190314)
	d2k: Dune 2000 (release-20190314)
	ra: Red Alert (release-20190314)
	ts: Tiberian Sun (release-20190314)
External mods:
	ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
	ra2-git-b9668d9: Red Alert 2 (git-b9668d9)
Loading mod: ra2
Xlib:  extension "NV-GLX" missing on display `":0".
```

Backtrace:
[bt.txt](https://github.com/OpenRA/ra2/files/3413909/bt.txt)

**Comment by abcdefg30** [comment]
Did the game not write any exception log?

**Comment by dchokola** [comment]
I am no longer certain which log corresponds with this issue, but I found three which look about right. Two of them seem related to `OpenRA.Mods.Common.Orders.PlaceBuildingOrderGenerator+<RenderAboveShroud>'. The earliest log has a different error and may be unrelated.
[exception-2019-07-20T185124Z.log](https://github.com/OpenRA/ra2/files/3414054/exception-2019-07-20T185124Z.log)
[exception-2019-07-20T171418Z.log](https://github.com/OpenRA/ra2/files/3414055/exception-2019-07-20T171418Z.log)
[exception-2019-07-20T165645Z.log](https://github.com/OpenRA/ra2/files/3414056/exception-2019-07-20T165645Z.log)

**Comment by GraionDilach** [comment]
Notsure why @abcdefg30 closed these without a memo, but all logs point towards the bugged 5.18 Mono version Debian/Ubuntu ships. See https://github.com/OpenRA/OpenRA/issues/16235 for further details.

**Comment by abcdefg30** [comment]
Thanks. We had talked on IRC about this, hence I closed the issue.
