### ISSUE TITLE
add new house on old shp

### ISSUE THREAD

**Issue by genralduk** [OpenRA/ra2#582]
How can I build a new house based on the old shp when I use the snow map and I build another map?

- I used the Tech Oil Derrick "caoild.shp" shp located at "~ isosnow.mix" when building a house on the snow map works but when I use another map I got a problem.

- I know that if you want to build on another foundation, you have to use another shp at "tech oil derick" I found it in "~ isotemp.mix" but I don't know how to declare Sequences so that when built on a foundation other than snow, the house I tried adding new shp to "~ generic.mix" but it still doesn't work

**Comment by yaaaaa** [comment]
Copy all of the Oil Derrick shps:
caoild.shp - for Arctic tilesets maps
ctoild.shp - for Temperate tilesets
cdoild.shp - for Desert
cuoild.shp - Urban
cnoild.shp - Newurban
cloild.shp - Lunar *if exist
Place your shps into bits folder.

Copy secuences from Tech Oil Derrick to Your building in sequences.yaml
Copy rules from Tech Oil Derrick to Your building in rules.yaml and edit it

**Comment by yaaaaa** [comment]
And the forum is the best way to talk about modding

**Comment by abcdefg30** [comment]
> And the forum is the best way to talk about modding

I agree. That is the better place.

**Comment by genralduk** [comment]
thank's yaaaaa verymuch for help me <3
thank's every body helped me
