### ISSUE TITLE
Multiplayer client maps missing

### ISSUE THREAD

**Issue by p1839251** [OpenRA/ra2#588]
Hello,
I tried playing in multiplayer mode but it wouldn't work.
Both computers are GNU/Linux based (Arch) systems and have the very same version of the game (913.git.dec7ca5) (installed from the AUR https://aur.archlinux.org/packages/openra-ra2-git/ ).
I created a server with either one but the client didn't find anything 'No games found, try changing filters.' After enabling the 'Incompatible filter', I could see a bunch of servers but I couldn't join any of them. However, using a direct ip + port 1234, I could join my local server but I wasn't able to check the 'Ready' checkbox.
The client said 'Unknown map. This map was not found on the OpenRA Resource Center'. This is weird, as I used a standard 'dustbowl' map (which is present on both machines and works well in singleplayer mode)

I copied 3 .mix files from the original CD, namely : ra2.mix, language.mix and theme.mix.
1234 port was open.

**Comment by GraionDilach** [comment]
Don't host dedicated servers, but host from a client.

There's nothing "weird" if the map is missing from the Resource Center, RA2 is progressing at a slow pace and if a version bump updated the internal maps, these new revisions weren't uploaded to the Resource Center. Considering the state of the repository, it's just better to host from the client, because if all players have the map already from a game hosted from the client, the Resource Center is excluded from the check.

**Comment by abcdefg30** [comment]
Yes, what Graion said. Imho it does not make sense to upload maps at the current state, so it indeed will be better if you host yourself.

**Comment by p1839251** [comment]
I still need a little help. I don't quite understand how I could 'host from a client'.
I made a screencast how I tried creating a game: https://filebin.net/jcr7oduw527lqewl/RA2.mp4?t=4c4konxr
I'll write down what's in the video in case it's unavailable:
OpenRA opens > Multiplayer > Create > Create > Waiting for the other player to join the game > and Start Game.

What should I do differently?

**Comment by abcdefg30** [comment]
You are doing everything right. This means you have different maps installed locally (map hash is different). You should make sure that both of you downloaded the same version of the mod.

**Comment by p1839251** [comment]
Ok, I've checked what you had suggested:
Version 913.git.dec7ca5 is installed on both machines.
I found the maps here: /usr/lib/openra-ra2/mods/ra2/maps/dustbowl
Hashes are the same on both:
fffac4fb20f660e0ce7a8728ffd6d11c  map.bin
0fe1c84dd877255ddc1bf066f77fe782  map.png
cb2f466e408c16ba48d6ba921106754f  map.yaml

Here is a video of the client: https://filebin.net/v3uujc1uscidsdau/openra2.mp4?t=m5eruzq9

If I'm still doing everything right then this must be a bug

**Comment by abcdefg30** [comment]
That is really weird. I just tested it with two machines on the same version and it worked (I am on Windows on both however). Do any other maps work? Do other mods also show this behaviour (for custom maps that are not on the resource site)?

**Comment by MarDiehl** [comment]
I have the same problem. Also on Arch linux, but using the release version (https://www.archlinux.org/packages/community/any/openra/).
One client creates a multiplayer game and the other player cannot join if certain maps (Snow Town, Six Below Zero) are selected.

**Comment by Mailaender** [comment]
Neither Snow Town nor Six Below Zero add custom rules or anything. Check the log files. It is probably something else.

**Comment by MarDiehl** [comment]
It seems that maps that are in a folder don't work. For example, `six-below-zero` is a folder which contains `map.bin`, `map.png`, `map.yaml` and `rules.yaml`. It does not work, the message of the client that joins is 'Unknown map. This map is not found on the OpenRA Resource Center'.
`sidestep` works. It is a single file called `sidestep.oramap`.
Both computers have the same version installed and the mentioned files are there.

**Comment by abcdefg30** [comment]
Hm. We suspect it might be because of differences in line endings on Linux (since it seems to work fine on Windows). Would you mind checking if they differ between your computers?

**Comment by MarDiehl** [comment]
On the two computers, it is the same.
But maybe the both differ from the resource center.

checksums are

```
six-below-zero sha256sum *
89edadd271925562c7c591ca08272c21c3a88157889b65b101ae25937a860c61  map.bin
fbccab795312104289b33bef19f48af994229da9b549105cf95ead53daccb8be  map.png
56cb122ddfec0cedeff2a91173809f558ae1384bead17902cd849bef794c8f7e  map.yaml
b12e7cdb94d106c5997af69681cdc9f1ccde91f916686e7d7e9802a868721cc7  rules.yam
```

**Comment by Mailaender** [comment]
Actually I was wrong https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/six-below-zero/rules.yaml are there for the weather. They were last changed in 2017, but apparently not updated on the resource center.

Do other maps like https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/maps/fort-lonestar or https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/maps/shattered-mountain work?

**Comment by MarDiehl** [comment]
I'm currently not sure about these two maps, but we have encountered this issue for multiple maps.
Probably it would be best to update all maps on the resource center.

**Comment by Mailaender** [comment]
Can you check if using the release tarballs https://github.com/OpenRA/OpenRA/archive/release-20200503.tar.gz instead of git fixes it?

**Comment by MarDiehl** [comment]
I already use the 20200503 release

**Comment by MarDiehl** [comment]
I have tried the tarball (install openRA on both computers) and it does not make a difference.
Also, the checksums of the files for six-below-zero are the same in the tarball as previously. The also match https://resource.openra.net/maps/22463/
