### ISSUE TITLE
request of new functionality => click one and buy 30 items

### ISSUE THREAD

**Issue by Adel1818** [OpenRA/ra2#589]
i ' m a web developer, & i love this game ...
i waste a lot of time on clicking 30 times to creat my army
best regards, you are doing a good job

**Comment by abcdefg30** [comment]
If you hold shift while queuing, you'll add 5 and not 1 new item to the queue. Is that the kind of feature you are looking for?

**Comment by Adel1818** [comment]
it's a good idea :)

**Comment by abcdefg30** [comment]
Ok. I think we can close this then.
