### ISSUE TITLE
Exception during GI/Prism Tank attack.

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [OpenRA/ra2#593]
[exception-2019-12-07T174244Z.log](https://github.com/OpenRA/ra2/files/3935379/exception-2019-12-07T174244Z.log)
[debug.log](https://github.com/OpenRA/ra2/files/3935380/debug.log)

**Comment by sorcerer86pt** [comment]
Hi
Can you please describe what happened/ steps to reproduce this crash?
