### ISSUE TITLE
Engine update needed: GeoLite2-Country.mmdb.gz can't be downloaded

### ISSUE THREAD

**Issue by fusion809** [OpenRA/ra2#598]
Hi,

GeoLite2-Country.mmdb.gz can't be downloaded using the scripts in this repo anymore, so the engine should be updated to later versions that do not attempt to download this file because at the moment trying to build this mod gives the error:

```bash
Fetching NUnit.Console from NuGet
Fetching Open.Nat from NuGet
Fetching FuzzyLogicLibrary from NuGet.
Fetching SDL2-CS from GitHub.
Fetching OpenAL-CS from GitHub.
Fetching Eluant from GitHub.
Fetching rix0rrr.BeaconLib from NuGet.
Updating GeoIP country database from MaxMind.
make[1]: *** [Makefile:317: geoip-dependencies] Error 6
make[1]: Leaving directory '/home/fusion809/AUR/openra-ra2-git/src/ra2/engine'
make: *** [Makefile:75: engine] Error 2
```

OpenRA/OpenRA#17561 is the upstream engine PR that fixed this issue.

Thanks for your time

**Comment by abcdefg30** [comment]
I'll hopefully update the engine to the latest release (doing a hop over 20191117) in the next days.

**Comment by abcdefg30** [comment]
Updated the engine version. The compiler warnings are expected/intentional and will go away once upstream OpenRA targets a more modern .NET version.
