### ISSUE TITLE
Build preview on Arch Linux only shows the squares the building will occupy, not what the building will look like

### ISSUE THREAD

**Issue by fusion809** [OpenRA/ra2#602]
Hi,

When one clicks on a building one's built and tries to place it somewhere, one sees the tiles the building will occupy in green (if the place is suitable for the building to be placed) or red (if the place is unsuitable), but there's no preview of what the building will look like above those tiles like there usually is. 

![Screenshot_20200123_112842 RA2 window only](https://user-images.githubusercontent.com/4717341/72949623-94617f00-3dd4-11ea-9054-52ba096bc219.png)

Thanks for your time

**Comment by abcdefg30** [comment]
That is intentional, since the original didn't have it either.
