### ISSUE TITLE
OpenRa ask me to install through Disc

### ISSUE THREAD

**Issue by asbis** [OpenRA/ra2#603]
I followed the tutorial to install it with terminal with the ra2-master.zip on a mac.

When running the game it ask me to install through disk. I dont have the game on disk, i neither have an CD player on my mac neither.

So when i try to follow the tutotorial to add the game manually, it ask me to add it to ~/Library/Application Support/OpenRA/Content/ra2/

This folder does not exist. The game is not installed in the mac. but it runs from the folder.

Where in the ra2-master folder should i add the game content?

**Comment by MustaphaTR** [comment]
Does ~/Library/Application Support/OpenRA/ not exist, or is it just ra2 subfolder. You should create ra2 folder yourself. If OpenRA doesn't exist i guess you never installed OpenRA on this device before. Try installing the basegame from https://www.openra.net/download/.

I think you can try creating the whole thing even if OpenRA folder doesn't exist, but i'm not sure if that would work in that case.

You can also try creating and putting it under ra2-master/engine/Support/Content/ra2, but i'm not sure if that's gonna work either without rest of the userdata stuff.

**Comment by asbis** [comment]
Thanks for your reply. I tried to add the folder myself and added the content to ~/Library/Application Support/OpenRA/Content/ra2/ 

Still, the game does not find the .mix files i am asked to add.


i tried to find the Support folder in engine in here:
ra2-master/engine/Support/Content/ra2
but could not find it.

**Comment by MustaphaTR** [comment]
There is no Support folder by default, you should create it. If Support folder exists, game reads the user data from there instead of its usual place.

If that doesn't work either, put the mixs in ra2-master/mods/ra2/bits. Then open ra2-master/mods/ra2/mod.yaml with a text editor and delete this line: https://github.com/OpenRA/ra2/blob/master/mods/ra2/mod.yaml#L295 or make it false, doesn't matter. This should certainly work.

**Comment by asbis** [comment]
Thanks!
it worked by making a folder Support/Content/ra2 and put the files there.

Cool game
Found some few bugs while trying the game. The planes try to land on the same spot for allies, and the soldiers does not move. But for the rest it seems like it worked great!

**Comment by abcdefg30** [comment]
Glad to hear you got it working. GIs not moving is already fixed in the newest version.

**Comment by PKUFlyingPig** [comment]
Where can I find the game content? Should I buy and download the game to get that?

**Comment by abcdefg30** [comment]
Yes, that would be the official way. You can also use the original disks (or images of them) if you have access to those.
