### ISSUE TITLE
Fixing the flags

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ra2#609]
In RV we've edited the country flags to properly match the colors they should be in, UI code uses 32-bit PNG files so there is no limitation there. A pretty obvibious mistake from WW is the German Flag being Black-Orange-Yellow instead of Black-Red-Yellow also the Cuban flag has 2 too many stripes. I'm not sure we would want to correct these issues or keep it as original.

**Comment by MustaphaTR** [comment]
@abcdefg30 @Mailaender Can i have a comment on this, it is an easy fix.

**Comment by Mailaender** [comment]
I assume you mean:

![this](https://raw.githubusercontent.com/OpenRA/ra2/master/mods/ra2/uibits/buttons.png)

Feel free to polish it up.

**Comment by MustaphaTR** [comment]
Yes, i'm talking about those flags.
