### ISSUE TITLE
Error MSB3644?

### ISSUE THREAD

**Issue by SkyFixing** [OpenRA/ra2#622]
I have followed all the advice the program has given by installing the right programs but it keeps giving me an error, I need help...

**Comment by abcdefg30** [comment]
Without seeing more of the error, this sounds to me like you have an outdated (or broken/incompatible) version of the .NET framework. Do you have version 4.6.1 or newer installed? (Download is at https://dotnet.microsoft.com/download/dotnet-framework/net461 )

**Comment by SkyFixing** [comment]
I downloaded it yesterday so I think it should be all up to date.
<img width="947" alt="6fbb157eba4a57a3072ff15e6aa0c993" src="https://user-images.githubusercontent.com/60647972/73825163-c5da4180-47fb-11ea-900d-5c36467167e8.png">

**Comment by SkyFixing** [comment]
I dont know if this helps but please reply as soon as possible please ^^

**Comment by abcdefg30** [comment]
Sorry, I don't really have another idea at the moment. The only other thing you could try is installing the *developer* pack from https://dotnet.microsoft.com/download/dotnet-framework/net461

**Comment by SkyFixing** [comment]
The Development kit worked for me, thanks :D

**Comment by abcdefg30** [comment]
Ok, good to hear. :)
