### ISSUE TITLE
attack dogs are at the moment useless

### ISSUE THREAD

**Issue by sorcerer86pt** [OpenRA/ra2#623]
At the moment attack dogs for both factions doesn't do anything:

- Can't attack
- Can't detect spys

only thing they can do is explore terrain.

**Comment by MustaphaTR** [comment]
It looks like ^Infantry is missing EdibleByLeap: but even after adding that and editing the weapon a bit to match upstream RA, i still couldn't get it to actually kill the units. They now jump but not deal any damage.

**Comment by sorcerer86pt** [comment]
So now they jump... For petting? 😋🥰👌

A terça, 18/02/2020, 4:19 da tarde, Mustafa Alperen Seki <
notifications@github.com> escreveu:
