### ISSUE TITLE
Polished Allied & Soviet Radar Image & HighRes macOS Bundle Icon.

### ISSUE THREAD

**Issue by ShikiSuen** [OpenRA/ra2#637]
See demo:
https://www.youtube.com/watch?v=YT99m19ksQE

![AlliedLogo](https://user-images.githubusercontent.com/3164826/75083536-9e55d980-555c-11ea-9603-73b302df5e8a.png)
![SovietLogo](https://user-images.githubusercontent.com/3164826/75083538-a0b83380-555c-11ea-8c61-5c3188274272.png)

**Comment by ShikiSuen** [comment]
![chrome](https://user-images.githubusercontent.com/3164826/75083576-f42a8180-555c-11ea-9a5d-5b654970404a.png)

**Comment by ShikiSuen** [comment]
Also macOS Packaging icon.
[mod.icns.zip](https://github.com/OpenRA/ra2/files/4238645/mod.icns.zip)

**Comment by Mailaender** [comment]
That looks like the macOS packaging icon from this repository not yours.

**Comment by Mailaender** [comment]
Feel free to send a pull request though. It seems to be a good idea to use your remade ones instead graphics that look like they were ripped from the original assets.

**Comment by ShikiSuen** [comment]
@Mailaender The default macOS packaging icon has too low resolution.
I provided the high resolution one, though I am not the original illustrator.

**Comment by ShikiSuen** [comment]
https://github.com/OpenRA/ra2/pull/638

**Comment by ShikiSuen** [comment]
The high res PNG files I posted in the 1st post of this thread can be used for further purposes if OpenRA is going to support 200% HiDPI UI image.

**Comment by Mailaender** [comment]
We suspect that you ripped assets from Red Alert 3 so we immediately had to replace them. #641 Please be more careful with copyright next time.

**Comment by ShikiSuen** [comment]
@Mailaender 
That's an immitation. The PSD file is here:
[AlliedLogo.zip](https://github.com/OpenRA/ra2/files/4243267/AlliedLogo.zip)

**Comment by ShikiSuen** [comment]
Furtherly, it is meaningless to rip UI assets from RA3.
RA3 is designed for 720p HD screens. Its UI assets are too blurry for modern 4k screens.

**Comment by ShikiSuen** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/3164826/75131655-6941b680-5717-11ea-93d2-e214e729d97e.png">

**Comment by ShikiSuen** [comment]
Comparatively, the RA3 EA official asset (black outline too bold):
<img width="188" alt="image" src="https://user-images.githubusercontent.com/3164826/75131741-c3427c00-5717-11ea-9ce4-22a9c44fba06.png">

**Comment by ShikiSuen** [comment]
Maybe OpenRA2 deserves a new design of logos for Allied, Soviet, and Yuri.

I will find some time in late March to do this redesign if convenient.

P.S.: 90% of your in-battle UI chrome elements are ripped from RA2.

**Comment by ShikiSuen** [comment]
I just checked RA3 again and found that my retraced Allied radar logo looks similar to the following one. However, please pay attention to the spacial distances among white objects (especially those spaces between the white triangle and the top side of the eagle wings).

Now @Mailaender you owe me an apology for your suspicion without sufficient reasoning. This is too hostile.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/3164826/75162944-b5b1e400-5761-11ea-8ef2-7f0f7c94b01a.png">

**Comment by Mailaender** [comment]
This was not meant to be hostile. It was just an observation by the @AttacqueSuperior community. We also sourced the soviet one to https://www.moddb.com/members/tomsons26/images/ra2-soviet-logo If you traced the same original emblem than I wouldn't wonder they look similar.

**Comment by ShikiSuen** [comment]
@Mailaender Then forget about the soviet one you rejected this time. I found the referenced image from another site months ago. Thank you for letting me know its real author.

I am gonna rePR the Allied one back in the next few days. The Soviet one requires retrace to match the Allied one I retraced.

**Comment by ShikiSuen** [comment]
@Mailaender 

I checked your new radar logo. They look too metalic / material-style which (my personal opinion) are not something self-luminescent. Your new logos may have better places to use (like the menu select of campaign missions, etc.).

Anyway, just now I use Affinity Designer to recreate radar logos for all three fractions.
Since Affinity Designer documents are all vectors, they can be resized as much as you wish.
(I will share the original project files of these logos. It is you people's matter to buy Affinity Designer.)

![YuriLogo](https://user-images.githubusercontent.com/3164826/75252146-692cde00-581f-11ea-9b41-db109ea37e5d.png)
![SovietLogo](https://user-images.githubusercontent.com/3164826/75252152-6b8f3800-581f-11ea-97e7-82534b33e26d.png)
![AlliedLogo](https://user-images.githubusercontent.com/3164826/75252164-7053ec00-581f-11ea-85e0-9f3730cd17cc.png)

**Comment by GraionDilach2** [comment]
Hello.

I was the original guy who traced back your assets. The Allied logo is still from Red Alert 3. Directly or indirectly, maliciously or just unknowingly - doesn't matter. The shape of the head, the omission of the eye are features of the RA3 Allied logo separating it from it's RA2 counterpart and your work features all of them. There's nothing to deny there and there's nothing to demand an apology for.

The new logos which got rushed in to fix your mistake not just are based on the community's most accurate RA2 logo remakes (where the metallic elements came from), but actually follow suit of Red Alert 2's own radar images with the background stripes, fitting in perfectly. Your remakes stick out like a sore thumb, even if we overlook the fact that you're still trying to submit the Red Alert 3 Allied logo. The pale background you're aiming for is another Red Alert 3 feature.

> P.S.: 90% of your in-battle UI chrome elements are ripped from RA2.

False. tomsons26 have retraced a lot of the RA2 UI elements with the same level of accuracy he put into the logos and x-a-n-a-x was allowed to base the artwork upon that. Your assumptions are wrong.

Just because you started with taking two random images from the Internet, assumed something about their copyright status and pulled them in that does not mean your predecessors have done the same.

**Comment by ShikiSuen** [comment]
@ghost

So you want a new shape with Allied radar icon?
Then it is about the time to try my new idea.
I will start a new issue thread when the Allied new icon shape design is finished.

`"There's nothing to deny there and there's nothing to demand an apology for."`
If I were you, I would overlap two Allied logo pictures, resize them to the same level, and compare pixel-to-pixel. You claim your works "retrace" but refuse to admit that my allied logo is also "retrace", that's where I see your hostility.

**Comment by ShikiSuen** [comment]
`"The pale background you're aiming for is another Red Alert 3 feature."`
So what are you aiming for?
Making the UI of this mod as aesthetically similar as original RA2?
My choice of pale backgrounds are thinking that your flavors are visually distracting to the players (in this radar image context) and may trigger trypophobia to some people. Logos are already drawn in detail, hence no necessary to make the backgrounds of the radar logo more sophisticated.

**Comment by ShikiSuen** [comment]
The official RA3 Allied logo has bended neck curves; mine behaves differently. (My vector rebuild doesn't use curves in eagle neck.)
Please also pay attention to the shape of the eagle back-head fur.

I tweaked the logo a little, making some differences to the shoulders and the tail.
<img width="876" alt="image" src="https://user-images.githubusercontent.com/3164826/75406137-063c6380-5953-11ea-90ba-1cf1c075128b.png">

Also the gradients used in the background:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/3164826/75406334-8d89d700-5953-11ea-8a5e-3a9697a56c29.png">

**Comment by ShikiSuen** [comment]
Tweaking soviet icons to improve the shadow inside the pentagon:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/3164826/75407700-f9ba0a00-5956-11ea-9488-b6c57d36809e.png">

**Comment by Mailaender** [comment]
> <img alt="image" width="681" src="https://user-images.githubusercontent.com/3164826/75438734-d5cce780-599b-11ea-92af-671c1f367cab.png">
> 

You may want to submit this to https://github.com/cookgreen/Yuris-Revenge/ instead.

**Comment by ShikiSuen** [comment]
@Mailaender Already there:
https://github.com/cookgreen/Yuris-Revenge/pull/102

**Comment by ShikiSuen** [comment]
I am putting the latest Affinity Designer project files into this repo for easier management:
https://github.com/ShikiSuen/OpenRA-YR-Noble-UI-Chrome-Assets
