### ISSUE TITLE
No credits file to be found

### ISSUE THREAD

**Issue by Metadorius** [OpenRA/ra2#642]
Title pretty much says it's all. I was going to credit artwork authors in #641 but there's no suitable file to write credits into.

**Comment by abcdefg30** [comment]
I created https://github.com/OpenRA/ra2/wiki/Authors long ago (and still maintain that) before adding AUTHORS to the repository was feasible. (Conflicts with OpenRA's AUTHORS file.)

**Comment by ShikiSuen** [comment]
Could any of you please help me check this PR?:
https://github.com/OpenRA/ra2/pull/645

I must say that https://github.com/OpenRA/ra2/pull/641 are well crafted, but there are other better in-game places to use them.

**Comment by Mailaender** [comment]
We need that distributed together with the source for GPL compliance.
