### ISSUE TITLE
mpspawn is invisible after being placed in the map editor

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/ra2#678]
Other actors are fine.

**Comment by Mailaender** [comment]
Actually they can be placed, they just stay invisible.

**Comment by sorcerer86pt** [comment]
![Base Profile Screenshot 2020 03 19 - 11 06 05 68](https://user-images.githubusercontent.com/11853415/77061200-c86eb000-69d1-11ea-848a-3d122b8a17bd.png)
map spawn point is visible after placement now
