### ISSUE TITLE
Provide Appimages / installers

### ISSUE THREAD

**Issue by eX00r** [OpenRA/ra2#697]
Saddly many of my friends are not able to install this mod properly (nor Win10 or Ubuntu 18.04+) with the help of your wiki. It would be so cool to have a handy installer and an AppImage for Linux. That does not seem to be to hard, if you know how to do it. Unfortunately, I don't. :(

**Comment by Mailaender** [comment]
I understand your frustration, but we believe it isn't ready yet. See also #387

**Comment by eX00r** [comment]
Hello,
 little up for this topic. How about providing a devtest Appimage i.e.?
