### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by Kimochii-x3** [OpenRA/ra2#720]
I have original RA2 from origin purchased pack and installed with Yuri's revenge
I have OpenRA installed and have put ra2-master inside of it
I have microsoft visual studio and .NET core 3.1.2 (or something like that) with .NETFramework installed (v4.8) however I can't find it in the installed programs on windows 10
I'm getting the error "MSB3644" from which the build fails, I tried following the wiki but it is not understandable for me (making a video tutorial would be best covering all 3 parts of the wiki)

I can't find anything helpful (nor do I know how to properly search for it) to resolve the issue.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/blob/release-20200202/INSTALL.md#windows on how to install the dependencies you seem to be missing.

**Comment by Kimochii-x3** [comment]
I have visual studio 2017 installed and some community version of it as well
after I opened the OpenRA.sln I have output with the following line:
<filename and path to it> : error : The SDK 'Microsoft.NET.Sdk' specified could not be found. <filename and path to it>

Following up with mitigation report
![image](https://user-images.githubusercontent.com/38957871/81862327-75445400-9561-11ea-9923-df8f1892d9f3.png)

I also am not a keen fan of visual studio and haven't used it, so I have no idea what is msbuild or how to use it, by no means I am any sort of smart individual or developer, just a fan of ra2 because I played it non stop as a kid (along with starcraft and other games of the like)

**Comment by Kimochii-x3** [comment]
The issue got resolved after I opened visual studio code's installer and made it install .net sdk, core and all those to the latest possible versions.
