### ISSUE TITLE
Errors for Mono

### ISSUE THREAD

**Issue by Guo-Zhang** [OpenRA/ra2#736]
/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild: line 3: /Library/Frameworks/Mono.framework/Versions/4.6.2/bin/mono: Bad CPU type in executable

What's the possible reason for that? I am sorry that I am new to C#. Thanks!

**Comment by abcdefg30** [comment]
Looks like you are using mono version `4.6.2`. We require a minimum of `5.18` (see https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md#linux).

**Comment by Guo-Zhang** [comment]
Thanks! I have update it.
