### ISSUE TITLE
Errors when running make all on macOS

### ISSUE THREAD

**Issue by Guo-Zhang** [OpenRA/ra2#737]
OpenRA.PostProcess -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.PostProcess.exe
  OpenRA.Game -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Game.exe
  OpenRA.Mods.Common -> /Users/zhangguo/Codes_Source/ra2-master/engine/mods/common/OpenRA.Mods.Common.dll
  OpenRA.Mods.Cnc -> /Users/zhangguo/Codes_Source/ra2-master/engine/mods/common/OpenRA.Mods.Cnc.dll
  OpenRA.Utility -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Utility.exe
  OpenRA.Server -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Server.exe
  OpenRA.Mods.D2k -> /Users/zhangguo/Codes_Source/ra2-master/engine/mods/d2k/OpenRA.Mods.D2k.dll
  OpenRA.Platforms.Default -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Platforms.Default.dll
  OpenRA.Test -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Test.dll
  Restore completed in 85.66 ms for /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj.
  Restore completed in 0.92 ms for /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.PostProcess/OpenRA.PostProcess.csproj.
  Restore completed in 3.54 ms for /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj.
  Restore completed in 1.56 ms for /Users/zhangguo/Codes_Source/ra2-master/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj.
  Restore completed in 0.68 ms for /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Game/OpenRA.Game.csproj.
  OpenRA.PostProcess -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.PostProcess.exe
  OpenRA.Game -> /Users/zhangguo/Codes_Source/ra2-master/engine/OpenRA.Game.exe
  OpenRA.Mods.Common -> /Users/zhangguo/Codes_Source/ra2-master/engine/mods/common/OpenRA.Mods.Common.dll
  OpenRA.Mods.Cnc -> /Users/zhangguo/Codes_Source/ra2-master/engine/mods/common/OpenRA.Mods.Cnc.dll
Traits/Conditions/GrantTimedConditionOnDeploy.cs(127,26): error CS0539: 'GrantTimedConditionOnDeploy.CanIssueDeployOrder(Actor)' in explicit interface declaration is not found among members of the interface that can be implemented [/Users/zhangguo/Codes_Source/ra2-master/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj]
Traits/Conditions/GrantTimedConditionOnDeploy.cs(82,89): error CS0535: 'GrantTimedConditionOnDeploy' does not implement interface member 'IIssueDeployOrder.CanIssueDeployOrder(Actor, bool)' [/Users/zhangguo/Codes_Source/ra2-master/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj]
make: *** [core] Error 1

**Comment by abcdefg30** [comment]
This looks like you are trying to run this mod with a newer engine version than we support. The current engine version this mod uses is `release-20200202`.

**Comment by Guo-Zhang** [comment]
Thanks, it works.

But I find that I made a lot of exe files, and I am wondering whether I can run the game on macOS? How to make it? 

I use `make all` command.

**Comment by abcdefg30** [comment]
On mac you should only need to run `make` and then `launch-game.sh`.

**Comment by Guo-Zhang** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/13083271/86272426-20d46100-bc01-11ea-94ae-3a5a74403b29.png">

Thanks, it works! But it fails to download.

**Comment by Mailaender** [comment]
Try this script https://gist.github.com/Mailaender/1c9962667f1c453598523db8be51b9bc

**Comment by Guo-Zhang** [comment]
This script returns a 404 error when downloading from xwis.net. It seems that the resources doesn't exist on the website.

**Comment by Mailaender** [comment]
Updated it. Not sure why the URLs change all the time. See also https://xwis.net/forums/index.php/topic/177134-downloads/

**Comment by Guo-Zhang** [comment]
Thanks! I can successfully run the game now!

It is a great engine! You guys are so great!

I am sorry to find that there are some features and bugs when I am trying on that. How can I feedback the problems to your team? Is there any social group or email list?

In addition, I am interested in helping you to translate the engine into Chinese. What can I do for that?

**Comment by Mailaender** [comment]
https://www.openra.net/community/ or this bug tracker.

**Comment by Guo-Zhang** [comment]
Thanks!
