### ISSUE TITLE
just some remarks

### ISSUE THREAD

**Issue by dkwo** [OpenRA/ra2#740]
Nice job, thank you.
On Arch Linux, you also want mono-msbuild and cabextract as dependecies.
Moreover, it would be usefull to add to the wiki that one needs to *create* folder ra2-master/engine/Support/Content/ra2 and place there the two files extracted from Game1.cab

**Comment by Phrohdoh** [comment]
> Moreover, it would be usefull to add to the wiki that one needs to create folder ra2-master/engine/Support/Content/ra2 and place there the two files extracted from Game1.cab

OpenRA deliberately does not recommend installing assets _into_ (a git clone of) the engine directly.

https://github.com/OpenRA/OpenRA/wiki/Game-Content#manual-installation-not-recommended details manual installation of assets, if you need to go that route.

[RA2 supports automatically detecting and installing from](https://github.com/OpenRA/ra2/tree/43f28ea094935e39ed9187330fb841c509cde138/mods/ra2/installer):
- the first decade
- origin
- discs

**Comment by dkwo** [comment]
I seee, thanks.
I didn't find an option to install via the .cab file though, only cd or download, which are more cumbersome to me.
Do you know a better way to install using .cab file?

**Comment by Phrohdoh** [comment]
I believe I have manually used `cabextract`, as you mentioned, previously then manually installed the assets.
So no, I don't know of a better way, or if another way is planned for RA2, currently.  Sorry about that.
