### ISSUE TITLE
Traits/Conditions/GrantTimedConditionOnDeploy.cs(82,89): error CS0535: 'GrantTimedConditionOnDeploy' does not implement interface member 'IIssueDeployOrder.CanIssueDeployOrder(Actor, bool)' [/Users/catalina/Downloads/OpenRA2/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj]

### ISSUE THREAD

**Issue by benjamin-yin001** [OpenRA/ra2#741]
OpenRA.Mods.Cnc -> /Users/catalina/Downloads/OpenRA2/engine/mods/common/OpenRA.Mods.Cnc.dll
Traits/Conditions/GrantTimedConditionOnDeploy.cs(127,26): error CS0539: 'GrantTimedConditionOnDeploy.CanIssueDeployOrder(Actor)' in explicit interface declaration is not found among members of the interface that can be implemented [/Users/catalina/Downloads/OpenRA2/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj]
Traits/Conditions/GrantTimedConditionOnDeploy.cs(82,89): error CS0535: 'GrantTimedConditionOnDeploy' does not implement interface member 'IIssueDeployOrder.CanIssueDeployOrder(Actor, bool)' [/Users/catalina/Downloads/OpenRA2/OpenRA.Mods.RA2/OpenRA.Mods.RA2.csproj]
make: *** [core] Error 1

engine version = release-20200503

**Comment by abcdefg30** [comment]
This mod doesn't work with that engine version, see #738. You'll have to use 20200202.
