### ISSUE TITLE
A better description of what the mod is.

### ISSUE THREAD

**Issue by jeancallisti** [OpenRA/ra2#758]
Take a look at those pages : 
https://github.com/OpenRA/ra2
https://github.com/OpenRA/ra2/wiki

Both pages state that "this is a Red Alert 2 mod for OpenRA".

To me, this is not a good enough description of what the software does.
A few possible interpretations : 
- This uses the original RA2 files to create a game with the entire content of RA2 (in other words : This is a full RA2), the only technical difference being that is uses the OpenRA engine under the hood 
- This only recreates a multiplayer clone of RA2 (no recreation of campaign missions or cutscenes), but all RA2 units fully functional,
- This creates a Red Alert 1 clone, but with a RA2 skin.

**Comment by Zsombi55** [comment]
I was wondering about the same thing. The installation instructions are also quite unclear. First it states that it is a mod for the OpenRA engine.. but then it states that it requires files from the original RA2 game.

Let's say I have a fresh OS install and wish to try OpenRA2 out. How to go about it? The Wiki isn't actually helpful. Do I need a RA2 install first if not then where do I get the asked RA2 files?

Whenaking instructions always make it so even computer illiterates can understand.

**Comment by Mailaender** [comment]
[Update the wiki](https://github.com/OpenRA/ra2/wiki/Home/_compare/8b2c8f78207fa41e2b3a7a9f13b226c1ba16caf7...649c5051dc63c1d32f74c1b2e79c522d60cbece1) with a description answering your questions.

A screenshot in the README might also help clarify this in an instant:
![Screenshot](https://www.united-forum.de/data/media/high/768.jpg)
