### ISSUE TITLE
Screen flicker when window isn't active

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/ra2#768]
When alt+tabbing out of RA2 on a Windows dual monitor PC, the screen flickers rapidly between the game and a black screen, with screen tearing.

**Comment by penev92** [comment]
You should test TS and report upstream as this won't be a mod-specific issue. Also are you running the game in fullscreen? Best include a screenshot of your ingame settings panel and OS info.

**Comment by pizzaoverhead** [comment]
It's intermittent, but I haven't seen it in TS bleed yet. OS is Win7 x64 SP1. I'll try to narrow it down.

![RA2 settings](https://user-images.githubusercontent.com/3650108/108780094-d58c0b80-755f-11eb-84c2-3051efd72a80.png)

**Comment by abcdefg30** [comment]
That sounds more like a bug with graphic cards drivers. Also Windows 7 is no longer supported. If this is indeed an OpenRA bug it would be better if you can report it in the main repository since it is unlikely this mod is causing it alone. (Checking TS would be really helpful.)
