### ISSUE TITLE
Spy uses wrong dog sprite

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/ra2#771]
When the spy disguises itself as an attack dog, it uses the dog of the player's country instead of that of the target country, e.g. if the player is Allies, disguising as a Soviet Siberian husky attack dog will show an Allied German shepherd attack dog.

**Comment by zouyonghao** [comment]
It seems this bug is fix with https://github.com/OpenRA/OpenRA/commit/b4edec215e30adc5afb539997b3c8d685e91ca08#diff-1a778912415de13b0b03d3e5925fe93c6c37c2f7d484fd3bdce8154fd8a87d6b

**Comment by Shin-Aska** [comment]
> It seems this bug is fix with [OpenRA/OpenRA@b4edec2#diff-1a778912415de13b0b03d3e5925fe93c6c37c2f7d484fd3bdce8154fd8a87d6b](https://github.com/OpenRA/OpenRA/commit/b4edec215e30adc5afb539997b3c8d685e91ca08#diff-1a778912415de13b0b03d3e5925fe93c6c37c2f7d484fd3bdce8154fd8a87d6b)

Yes, can confirm that the bug has indeed been fixed on the latest master copy.

![Screenshot_20220114_124721](https://user-images.githubusercontent.com/8596711/149453470-65b7fea6-9680-4c5d-90a3-b61fef2221cf.png)
