### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by Bashdog** [OpenRA/ra2#773]
I cannot find open servers for ra2 (multiplayer). Is there a way to play ra2 with your friends without hosting an own server?

**Comment by abcdefg30** [comment]
Sorry, at the moment there is no stable version and no public servers.

**Comment by Bashdog** [comment]
Ok, could I use a Raspberry pi as a server instead? Is there a server image?

**Comment by abcdefg30** [comment]
I'm not sure if a pi will have enough performance, but you can try that. You would have to download and compile the source and then use the `launch-dedicated.sh` script.

**Comment by Bashdog** [comment]
It worked but I get the error: "Warning: Server port is not accessible from the internet.", so how can I make it accessible to the internet?

**Comment by Bashdog** [comment]
I have done port forwarding (port 1234 --> raspberry pi), so what is missing?

**Comment by abcdefg30** [comment]
If the master server can't ping the server but port forwarding is set up correctly my only guess is some sort of other firewall issue. (The game uses TCP btw.)
