### ISSUE TITLE
Cannot compile: Missing msbuild

### ISSUE THREAD

**Issue by david-0609** [OpenRA/ra2#774]
msbuild: command not found
I have tried installing microsoft .NET and .NET core to fix this, but it did not work.
System: Fedora 34

**Comment by EasonWang01** [comment]
You can type `mono` command to see if it's available in your terminal.

**Comment by david-0609** [comment]
`mono` is available on my terminal

**Comment by abcdefg30** [comment]
You might need to install `mono-devel`, I don't remember if the regular mono package comes with msbuild.

**Comment by david-0609** [comment]
> You might need to install `mono-devel`, I don't remember if the regular mono package comes with msbuild.

I have installed mono-devel, maybe it might be an issue with specifying the path to it?

**Comment by Mailaender** [comment]
Install `msbuild` from https://www.mono-project.com/download/stable/
