### ISSUE TITLE
Cannot make the file

### ISSUE THREAD

**Issue by Kridtakarn** [OpenRA/ra2#779]
I have problem with
 
``` 
kridtakarn  ~  ra2  make
make[1]: Entering directory '/home/kridtakarn/ra2/engine'
make[1]: Leaving directory '/home/kridtakarn/ra2/engine'
make[1]: Entering directory '/home/kridtakarn/ra2/engine'
It was not possible to find any installed .NET SDKs.
Install a .NET SDK from:
  https://aka.ms/dotnet-download
It was not possible to find any installed .NET SDKs.
Install a .NET SDK from:
  https://aka.ms/dotnet-download
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.6.1-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. [/home/kridtakarn/ra2/engine/OpenRA.PostProcess/OpenRA.PostProcess.csproj]
make[1]: *** [Makefile:155: core] Error 1
make[1]: Leaving directory '/home/kridtakarn/ra2/engine'
make: *** [Makefile:111: engine] Error 2
```
please help me

**Comment by Mailaender** [comment]
Try reading the error message yourself:
> It was not possible to find any installed .NET SDKs.
> Install a .NET SDK from:
>  https://aka.ms/dotnet-download

**Comment by Kridtakarn** [comment]
Still have problem
 ` ` `kridtakarn`  ~  ra2  make                                           master 
make[1]: Entering directory '/home/kridtakarn/ra2/engine'
make[1]: Leaving directory '/home/kridtakarn/ra2/engine'
make[1]: Entering directory '/home/kridtakarn/ra2/engine'
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.6.1-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. [/home/kridtakarn/ra2/engine/OpenRA.PostProcess/OpenRA.PostProcess.csproj]
make[1]: *** [Makefile:155: core] Error 1
make[1]: Leaving directory '/home/kridtakarn/ra2/engine'
make: *** [Makefile:111: engine] Error 2
 ` ` `

**Comment by Mailaender** [comment]
Could be because @penev92 put the repository in a broken state. I don't see any CI checks running. See if https://github.com/OpenRA/ra2/pull/778 fixes it for you.

**Comment by penev92** [comment]
Broken how exactly?
Engine is aligned to `release-20200503` and the SDK scripts are aligned to the exact corresponding version. Everything builds & runs and there are no CI checks because Travis is dead.
I would recommend going for the updated version of #778, but this sounds more to me like the broken mono situation. @Kridtakarn see if any of this helps:
> ubuntu doesn't have msbuild at all
you need to follow https://www.mono-project.com/download/stable/#download-lin-ubuntu
those instructions are linked from openra's installation documentation but not mods
if you add the mono repository and then update/install `mono-devel` it should hopefully just work

**Comment by penev92** [comment]
As far as I understand from [the Mono website](https://www.mono-project.com/docs/about-mono/compatibility/), the latest version of it should be compatible with both .NET Framework 4.6 and 4.7, so get the latest Mono.

**Comment by Mailaender** [comment]
Try https://aur.archlinux.org/packages/openra-ra2-git

**Comment by Kridtakarn** [comment]
### [SOLVED] Arch linux have broken Mono official repositories.

I solved the problem. Arch have broken Mono official repositories. Its maintainer is bad. 
This is my command for solve it. I recommended it for other Arch user who want to build OpenRA/RA2.

```
mkdir -p /tmp/mono-deb
cd /tmp/mono-deb                                             
curl https://download.mono-project.com/repo/ubuntu/pool/main/m/mono/mono-roslyn_6.12.0.147-0xamarin17+ubuntu2004b1_all.deb > mono.deb                          
ar p mono.deb data.tar.xz | tar xJf - ./usr/lib/mono/4.5/System.Reflection.Metadata.dll --strip-components 5
sudo mv /usr/lib/mono/4.5/System.Reflection.Metadata.dll /usr/lib/mono/4.5/System.Reflection.Metadata.dll_OLD
sudo cp System.Reflection.Metadata.dll /usr/lib/mono/4.5
```

For more information.
https://github.com/KSP-CKAN/CKAN/issues/3361
