### ISSUE TITLE
Adding game assets from Origin to OSX

### ISSUE THREAD

**Issue by allynsweet** [OpenRA/ra2#790]
I purchased the CnC Bundle from Origin on PC, but want to play from my MacBook. The game folder contains a DATA directory containing many .MEG files, and a subdirectory titled CNCDATA/RED_ALERT containing subfolders with .MIX files. Do you know which MIX files are required to make RA2 run on MacOS from the Origin bundle download?
Thank you!

**Comment by abcdefg30** [comment]
You want `ra2.mix`, `language.mix` and `theme.mix`. See https://github.com/OpenRA/ra2/wiki#installing-the-content-manually.

**Comment by allynsweet** [comment]
Thank you, however I couldn't find those in the CnC Ultimate Bundle from Origin. However, I was able to resolve this by building the game on PC from the bundle, and then taking those specific files from the PC build and transferring them over to OSX.
