### ISSUE TITLE
Hi devs, could you please update the engine of this mod?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/ra2#793]
We are trying to use this mod as one of the experiment of our 3D model and VXL rendering (unfortunately, we build those function based on newst openra commit) in order to see if our solution can adapt the overall art style of RA2. However, soon we get defeated by glitched tileset, disapeared UI and many things we don't know where to update and how to update. We would appreciate that if you can update the mod and engine here.

some of the pics of our process here, we really want to have a try in RA2:
![222557_657c586b_5520220](https://user-images.githubusercontent.com/13763394/174844527-86306430-8110-4191-956e-c4c4c6636685.png)

**Comment by abcdefg30** [comment]
The engine will be updated only after the next stable OpenRA release is out (since we don't update to intermediate bleed versions).

**Comment by Mailaender** [comment]
Done in https://github.com/OpenRA/ra2/pull/806.

**Comment by Mailaender** [comment]
> since we don't update to intermediate bleed versions

We really should. I had to wait 2 years and https://github.com/OpenRA/ra2/pull/652 is still not in.

**Comment by abcdefg30** [comment]
We discussed this with the ModSDK in mind as well: One idea is to branch off a `bleed` branch that can follow the upstream bleed branch. Since we don't have releases here anyway, we could also relax the convention a bit and update the engine if necessary.
