### ISSUE TITLE
very low fps on my system

### ISSUE THREAD

**Issue by Eitetsu0** [OpenRA/ra2#796]
Please tell me how can I debug it . or anything I could do.

Note the right bottom
![sc_20220801_011757](https://user-images.githubusercontent.com/6576065/182039334-68013f9a-3d23-42c5-a3d0-7ed13e668e8c.png)

Here's the console output :
```
❯ ./launch-game.sh
Platform is Linux
Engine version is release-20210321
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 2560x1440
No custom resolution provided, using desktop resolution
Using resolution: 2560x1440
Using window scale 1.00
OpenGL renderer: AMD Radeon RX 560 Series (polaris11, LLVM 14.0.6, DRM 3.46, 5.18.15-zen1-1-zen)
OpenGL version: 4.6 (Core Profile) Mesa 22.1.4
Using default sound device
Internal mods:
	ra2: Red Alert 2 ({DEV_VERSION})
	d2k: Dune 2000 (release-20210321)
	all: All mods (release-20210321)
	modcontent: Mod Content Manager (release-20210321)
	cnc: Tiberian Dawn (release-20210321)
	ts: Tiberian Sun (release-20210321)
	ra: Red Alert (release-20210321)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	ra2-{DEV_VERSION}: Red Alert 2 ({DEV_VERSION})
Loading mod: ra2
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
[2022-08-01T00:43:49] Game started
```

It also too took very looong time to load a saved game (almost 1 hour) .
During it's loading saved game , 1 cpu core is on 100% util.

Here is my system:
```
OS: Arch Linux x86_64 
Host: B450M AORUS ELITE 
Kernel: 5.18.15-zen1-1-zen 
Resolution: 2560x1440 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD ATI Radeon RX560
Memory: 4030MiB / 32040MiB 
```

**Comment by Eitetsu0** [comment]
I'm not sure will this help
![sc_20220801_022228](https://user-images.githubusercontent.com/6576065/182040075-e74db42f-067f-4ba0-970a-2d3913665bab.png)

**Comment by abcdefg30** [comment]
Judging from the radar this is probably https://github.com/OpenRA/OpenRA/issues/12435 because you destroyed the bridges?

**Comment by Eitetsu0** [comment]
> Judging from the radar this is probably [OpenRA/OpenRA#12435](https://github.com/OpenRA/OpenRA/issues/12435) because you destroyed the bridges?

Yea... I guess so.
