### ISSUE TITLE
Packaging fails on Arch Linux

### ISSUE THREAD

**Issue by fusion809** [OpenRA/ra2#805]
I currently get the error message:

```bash
cp: cannot stat '/path/to/ra2/packaging/linux/../..//./engine/bin/OpenRA.Mods.RA2.dll': No such file or directory
```

whenever I run `packaging/linux/buildpackage.sh` after building this mod with `make`.

**Comment by penev92** [comment]
Hello. I assume you're running the master branch, which is targeting .NET 4.7. If so it would probably not be worthwhile to try and investigate that.
I have started updating the mod for the upcoming OpenRA release and you can find that here - https://github.com/penev92/ra2/tree/updateModTo202212-devtest. Try packaging that and tell me how that goes.

**Comment by abcdefg30** [comment]
We don't package the TS mod, so this one shouldn't be either.

**Comment by penev92** [comment]
That won't be included in the pull request I make. If you look at that branch the packaging script is added in the very last commit called "Add GH packaging workflow temporarily". I needed to test packaging to verify that things are working and will drop it before making a PR.

**Comment by fusion809** [comment]
@penev92 Your branch builds the AppImage fine. Although I also build a package for this mod for Arch. Here is its chief packaging file, its PKGBUILD https://github.com/fusion809/openra-ra2-git/blob/master/PKGBUILD. For some reason each time I try to run openra-ra2 from it I get the error:

```bash
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000019 from typeref (expected class 'System.Diagnostics.Debugger' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000019 from typeref (expected class 'System.Diagnostics.Debugger' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
```

I also tried https://github.com/fusion809/openra-ra2-git/blob/master/PKGBUILD.backup, which crashed with the same error, even though a very similar PKGBUILD manages to build and run the Romanovs Vengeance mod just fine.

**Comment by fusion809** [comment]
If you could list which files need to be included in the package in order for it to run, that may suffice for me to be able to fix this issue myself. I know *.dll files, *.so files, *.exe files and mods/{ra2,common,modcontent} must be included. Anything else?

**Comment by fusion809** [comment]
Ah, after some bug-fixing of my own, I got it to install and launch the game effectively. Thanks.

**Comment by penev92** [comment]
@fusion809 any fixes that we need to do to our scripts? Or was it just your system?

**Comment by fusion809** [comment]
@penev92 Na, just needed to tweak my packaging files to put the files in the right locations and launch the game using the right command.
