### ISSUE TITLE
Build fails on windows 

### ISSUE THREAD

**Issue by joker5bb** [OpenRA/ra2#807]
I have installed all the dependencies from the wiki 

C:\Users\Admin\Downloads\ra2-master>make all
Building in Release configuration...
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: --nologo

For switch syntax, type "MSBuild -help"
Build failed. If just the development tools failed to build, try installing Visual Studio. You may also still be able to run the game.

Building ra2 in Release configuration...
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: --nologo

For switch syntax, type "MSBuild -help"
Build failed. If just the development tools failed to build, try installing Visual Studio. You may also still be able to run the game.

How can I fix this issue?

**Comment by penev92** [comment]
The fact that you are running `make all` instead of `./make.ps1 all` and the fact that you are getting an MSBuild error makes me think you are somehow running the Linux Makefile instead of the Windows build script, *and* perhaps trying to use Mono (??) Instead of .NET6

**Comment by CortexReaver** [comment]
No luck either 

![03-06-2023 151711](https://github.com/OpenRA/ra2/assets/34350690/f9914ed8-9f6e-4241-bc77-fa8dde6129bd)

**Comment by CortexReaver** [comment]
This instruction gives you links to older .NET Framework, I think this might be a reason.
https://github.com/OpenRA/OpenRA/blob/release-20200202/INSTALL.md

**Comment by CortexReaver** [comment]
And now it finally builds.
![03-06-2023 153339](https://github.com/OpenRA/ra2/assets/34350690/65c2a21e-cf3e-4d6a-a036-426037b1a463)

But it seems that there is no "dependencies" command in "make" script.
![03-06-2023 153546](https://github.com/OpenRA/ra2/assets/34350690/f0a47bd0-0194-41ea-81fe-153af0e0a807)

**Comment by abcdefg30** [comment]
> This instruction gives you links to older .NET Framework, I think this might be a reason. https://github.com/OpenRA/OpenRA/blob/release-20200202/INSTALL.md

Those are the instructions for a release from 02-02-2020! https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md contains the newest instructions. `make dependencies` is no longer needed. But seems like you worked the issues out regardless. 👍
