### ISSUE TITLE
IndexOutOfRangeException in FootprintBounds

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/ra2#85]
1)Start play 1x1 vs CPU
2)destroy his conyard
2)let him get create (he gets MCV)
3)CPU put conyard in place that very close to top map border
4)CPU start constract buildings in fog of war
5)I use chronosphere in CPU's warminner, witch frozen in fog border, near ore refinary.
6)and teleport it to clear ground in center of map
7)get Crach

Red Alert 2 Mod at Version {DEV_VERSION}
on map 3d2d49c6b064b99726e27ebfd92326e1ec4e0522 (DEFCON 6 by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Индекс находился вне границ массива.
   в OpenRA.Traits.FrozenActorLayer.FootprintBounds(FrozenActor fa) в d:\Games\OpenRA-bleed\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:строка 211
   в OpenRA.Traits.FrozenActorLayer.Add(FrozenActor fa) в d:\Games\OpenRA-bleed\OpenRA.Game\Traits\Player\FrozenActorLayer.cs:строка 199
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass5.<Created>b__4(Player player, Int32 playerIndex)
   в OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) в d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\PlayerDictionary.cs:строка 27
   в OpenRA.Mods.Common.Traits.FrozenUnderFog.Created(Actor self)
   в OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 232
   в OpenRA.World.CreateActor(String name, TypeDictionary initDict) в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 225
   в OpenRA.Mods.Common.Traits.PlaceBuilding.<>c__DisplayClass6.<ResolveOrder>b__2(World w)
   в OpenRA.World.Tick() в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 309
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 557
   в OpenRA.Game.LogicTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 582
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 709
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 749
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 117
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 39

**Comment by abcdefg30** [comment]
This is probably an upstream issue of OpenRA.
